// ============================================================================
// BoundNodes.Update — Update factory methods for every sealed BoundNode record.
//
// GENERATED by bound-nodes-gen.py from bound-nodes.schema.json.
// DO NOT EDIT by hand — edit the schema and re-run the generator.
//
// Update is the correct way for a rewriter to produce a modified node when the
// signature of the node type is unknown to the caller (i.e., in generated code).
// It mirrors Roslyn's BoundNodes.xml-generated `Update(...)` methods: each
// overload takes exactly the update-flagged constructor parameters; if ALL values
// are reference-equal (or value-equal for scalars) to the originals it returns
// `this`; otherwise it returns a `with`-clone with the new values.
//
// Rules:
//  - `BoundType` parameters are compared with ReferenceEquals (structural equality
//    on BoundType recurses through TypeSymbol.BoundView, causing stack overflow).
//  - Lists are compared by reference. Same-contents new list → new node.
//  - Span is NOT a parameter — it propagates from the original node unchanged.
// ============================================================================

using Esharp.Syntax;
using Esharp.Symbols;

namespace Esharp.BoundTree;


public partial record BoundCompilationUnit
{
    public BoundCompilationUnit Update(
        string? namespaceName,
        IReadOnlyList<BoundUsing> imports,
        IReadOnlyList<BoundMember> members
    )
    {
        if (namespaceName == NamespaceName
         && ReferenceEquals(imports, Imports)
         && ReferenceEquals(members, Members))
            return this;
        return this with { NamespaceName = namespaceName, Imports = imports, Members = members };
    }
}

// ---- Member ----
public partial record BoundFunctionDeclaration
{
    public BoundFunctionDeclaration Update(
        IReadOnlyList<BoundParameter> parameters,
        BoundType returnType,
        BoundBlockStatement body
    )
    {
        if (ReferenceEquals(parameters, Parameters)
         && ReferenceEquals(returnType, ReturnType)
         && ReferenceEquals(body, Body))
            return this;
        return this with { Parameters = parameters, ReturnType = returnType, Body = body };
    }
}

// ---- Member ----
public partial record BoundDataDeclaration
{
    public BoundDataDeclaration Update(
        IReadOnlyList<BoundField> fields,
        IReadOnlyList<BoundFunctionDeclaration> instanceMethods,
        IReadOnlyList<BoundInitDeclaration>? inits
    )
    {
        if (ReferenceEquals(fields, Fields)
         && ReferenceEquals(instanceMethods, InstanceMethods)
         && ReferenceEquals(inits, Inits))
            return this;
        return this with { Fields = fields, InstanceMethods = instanceMethods, Inits = inits };
    }
}

// ---- Member ----
public partial record BoundInitDeclaration
{
    public BoundInitDeclaration Update(
        IReadOnlyList<BoundParameter> parameters,
        BoundBlockStatement body,
        IReadOnlyList<BoundExpression>? baseArguments,
        IReadOnlyList<BoundExpression>? thisArguments
    )
    {
        if (ReferenceEquals(parameters, Parameters)
         && ReferenceEquals(body, Body)
         && ReferenceEquals(baseArguments, BaseArguments)
         && ReferenceEquals(thisArguments, ThisArguments))
            return this;
        return this with { Parameters = parameters, Body = body, BaseArguments = baseArguments, ThisArguments = thisArguments };
    }
}

// ---- Member ----
public partial record BoundNamespaceInitDeclaration
{
    public BoundNamespaceInitDeclaration Update(BoundBlockStatement body)
    {
        if (ReferenceEquals(body, Body)) return this;
        return this with { Body = body };
    }
}

// ---- Member ----
public partial record BoundNamespaceStateDeclaration
{
    public BoundNamespaceStateDeclaration Update(
        BoundExpression? computedGetter,
        BoundExpression? setterBody
    )
    {
        if (ReferenceEquals(computedGetter, ComputedGetter)
         && ReferenceEquals(setterBody, SetterBody))
            return this;
        return this with { ComputedGetter = computedGetter, SetterBody = setterBody };
    }
}

// ---- Member ----
public partial record BoundStaticFuncDeclaration
{
    public BoundStaticFuncDeclaration Update(
        IReadOnlyList<BoundField> fields,
        IReadOnlyList<BoundFunctionDeclaration> functions
    )
    {
        if (ReferenceEquals(fields, Fields)
         && ReferenceEquals(functions, Functions))
            return this;
        return this with { Fields = fields, Functions = functions };
    }
}

// ---- Member ----
public partial record BoundConstDeclaration
{
    public BoundConstDeclaration Update(
        BoundType type,
        BoundExpression value
    )
    {
        if (ReferenceEquals(type, Type)
         && ReferenceEquals(value, Value))
            return this;
        return this with { Type = type, Value = value };
    }
}

public partial record BoundBlockStatement
{
    public BoundBlockStatement Update(IReadOnlyList<BoundStatement> statements)
    {
        if (ReferenceEquals(statements, Statements)) return this;
        return this with { Statements = statements };
    }
}

public partial record BoundVariableDeclaration
{
    public BoundVariableDeclaration Update(
        BoundType declaredType,
        BoundExpression initializer
    )
    {
        if (ReferenceEquals(declaredType, DeclaredType)
         && ReferenceEquals(initializer, Initializer))
            return this;
        return this with { DeclaredType = declaredType, Initializer = initializer };
    }
}

public partial record BoundAssignment
{
    public BoundAssignment Update(
        BoundExpression target,
        BoundExpression value
    )
    {
        if (ReferenceEquals(target, Target)
         && ReferenceEquals(value, Value))
            return this;
        return this with { Target = target, Value = value };
    }
}

public partial record BoundIfStatement
{
    public BoundIfStatement Update(
        BoundExpression condition,
        BoundStatement then,
        BoundStatement? @else
    )
    {
        if (ReferenceEquals(condition, Condition)
         && ReferenceEquals(then, Then)
         && ReferenceEquals(@else, Else))
            return this;
        return this with { Condition = condition, Then = then, Else = @else };
    }
}

public partial record BoundWhileStatement
{
    public BoundWhileStatement Update(
        BoundExpression condition,
        BoundStatement body
    )
    {
        if (ReferenceEquals(condition, Condition)
         && ReferenceEquals(body, Body))
            return this;
        return this with { Condition = condition, Body = body };
    }
}

public partial record BoundReturnStatement
{
    public BoundReturnStatement Update(BoundExpression? expression)
    {
        if (ReferenceEquals(expression, Expression)) return this;
        return this with { Expression = expression };
    }
}

public partial record BoundExpressionStatement
{
    public BoundExpressionStatement Update(BoundExpression expression)
    {
        if (ReferenceEquals(expression, Expression)) return this;
        return this with { Expression = expression };
    }
}

public partial record BoundScopedMutCall
{
    public BoundScopedMutCall Update(
        BoundExpression receiver,
        BoundCallExpression call
    )
    {
        if (ReferenceEquals(receiver, Receiver)
         && ReferenceEquals(call, Call))
            return this;
        return this with { Receiver = receiver, Call = call };
    }
}

public partial record BoundTryStatement
{
    public BoundTryStatement Update(
        BoundBlockStatement body,
        IReadOnlyList<BoundCatchClause> catches
    )
    {
        if (ReferenceEquals(body, Body)
         && ReferenceEquals(catches, Catches))
            return this;
        return this with { Body = body, Catches = catches };
    }
}

public partial record BoundThrowStatement
{
    public BoundThrowStatement Update(BoundExpression? expression)
    {
        if (ReferenceEquals(expression, Expression)) return this;
        return this with { Expression = expression };
    }
}

public partial record BoundConstStatement
{
    public BoundConstStatement Update(
        BoundType type,
        BoundExpression value
    )
    {
        if (ReferenceEquals(type, Type)
         && ReferenceEquals(value, Value))
            return this;
        return this with { Type = type, Value = value };
    }
}

public partial record BoundRaiseStatement
{
    public BoundRaiseStatement Update(
        BoundType eventType,
        IReadOnlyList<BoundExpression> arguments
    )
    {
        if (ReferenceEquals(eventType, EventType)
         && ReferenceEquals(arguments, Arguments))
            return this;
        return this with { EventType = eventType, Arguments = arguments };
    }
}

public partial record BoundLetGuard
{
    public BoundLetGuard Update(
        BoundType declaredType,
        BoundExpression initializer,
        BoundBlockStatement elseBody
    )
    {
        if (ReferenceEquals(declaredType, DeclaredType)
         && ReferenceEquals(initializer, Initializer)
         && ReferenceEquals(elseBody, ElseBody))
            return this;
        return this with { DeclaredType = declaredType, Initializer = initializer, ElseBody = elseBody };
    }
}

public partial record BoundForEachStatement
{
    public BoundForEachStatement Update(
        BoundExpression collection,
        BoundStatement body
    )
    {
        if (ReferenceEquals(collection, Collection)
         && ReferenceEquals(body, Body))
            return this;
        return this with { Collection = collection, Body = body };
    }
}

public partial record BoundMatchStatement
{
    public BoundMatchStatement Update(
        BoundExpression subject,
        BoundType subjectType,
        IReadOnlyList<BoundMatchArm> arms
    )
    {
        if (ReferenceEquals(subject, Subject)
         && ReferenceEquals(subjectType, SubjectType)
         && ReferenceEquals(arms, Arms))
            return this;
        return this with { Subject = subject, SubjectType = subjectType, Arms = arms };
    }
}

public partial record BoundDeferStatement
{
    public BoundDeferStatement Update(BoundBlockStatement body)
    {
        if (ReferenceEquals(body, Body)) return this;
        return this with { Body = body };
    }
}

public partial record BoundAsyncLetStatement
{
    public BoundAsyncLetStatement Update(
        BoundType declaredType,
        BoundExpression initializer
    )
    {
        if (ReferenceEquals(declaredType, DeclaredType)
         && ReferenceEquals(initializer, Initializer))
            return this;
        return this with { DeclaredType = declaredType, Initializer = initializer };
    }
}

public partial record BoundYieldStatement
{
    public BoundYieldStatement Update(BoundExpression value)
    {
        if (ReferenceEquals(value, Value)) return this;
        return this with { Value = value };
    }
}

public partial record BoundSelectStatement
{
    public BoundSelectStatement Update(IReadOnlyList<BoundSelectArm> arms)
    {
        if (ReferenceEquals(arms, Arms)) return this;
        return this with { Arms = arms };
    }
}

public partial record BoundCompoundAssignment
{
    public BoundCompoundAssignment Update(
        BoundExpression target,
        BoundExpression value
    )
    {
        if (ReferenceEquals(target, Target)
         && ReferenceEquals(value, Value))
            return this;
        return this with { Target = target, Value = value };
    }
}

public partial record BoundUnaryExpression
{
    public BoundUnaryExpression Update(
        BoundExpression operand,
        BoundType type
    )
    {
        if (ReferenceEquals(operand, Operand)
         && ReferenceEquals(type, Type))
            return this;
        return this with { Operand = operand, Type = type };
    }
}

public partial record BoundBinaryExpression
{
    public BoundBinaryExpression Update(
        BoundExpression left,
        BoundExpression right,
        BoundType type
    )
    {
        if (ReferenceEquals(left, Left)
         && ReferenceEquals(right, Right)
         && ReferenceEquals(type, Type))
            return this;
        return this with { Left = left, Right = right, Type = type };
    }
}

public partial record BoundMemberAccessExpression
{
    public BoundMemberAccessExpression Update(
        BoundExpression target,
        BoundType type
    )
    {
        if (ReferenceEquals(target, Target)
         && ReferenceEquals(type, Type))
            return this;
        return this with { Target = target, Type = type };
    }
}

public partial record BoundConversion
{
    public BoundConversion Update(
        BoundExpression operand,
        BoundType targetType,
        ConversionKind kind
    )
    {
        if (ReferenceEquals(operand, Operand)
         && ReferenceEquals(targetType, TargetType)
         && kind == Kind)
            return this;
        return this with { Operand = operand, TargetType = targetType, Kind = kind };
    }
}

public partial record BoundTypeTestExpression
{
    public BoundTypeTestExpression Update(
        BoundExpression operand,
        BoundType targetType,
        bool negated
    )
    {
        if (ReferenceEquals(operand, Operand)
         && ReferenceEquals(targetType, TargetType)
         && negated == Negated)
            return this;
        return this with { Operand = operand, TargetType = targetType, Negated = negated };
    }
}

public partial record BoundCallExpression
{
    public BoundCallExpression Update(
        BoundExpression target,
        IReadOnlyList<BoundExpression> arguments,
        BoundType type,
        IReadOnlyList<BoundType>? explicitTypeArguments
    )
    {
        if (ReferenceEquals(target, Target)
         && ReferenceEquals(arguments, Arguments)
         && ReferenceEquals(type, Type)
         && ReferenceEquals(explicitTypeArguments, ExplicitTypeArguments))
            return this;
        return this with { Target = target, Arguments = arguments, Type = type, ExplicitTypeArguments = explicitTypeArguments };
    }
}

public partial record BoundObjectCreationExpression
{
    public BoundObjectCreationExpression Update(
        BoundType objectType,
        IReadOnlyList<BoundFieldInit> fields,
        IReadOnlyList<BoundExpression> constructorArguments
    )
    {
        if (ReferenceEquals(objectType, ObjectType)
         && ReferenceEquals(fields, Fields)
         && ReferenceEquals(constructorArguments, ConstructorArguments))
            return this;
        return this with { ObjectType = objectType, Fields = fields, ConstructorArguments = constructorArguments };
    }
}

public partial record BoundIndexExpression
{
    public BoundIndexExpression Update(
        BoundExpression target,
        BoundExpression index,
        BoundType type
    )
    {
        if (ReferenceEquals(target, Target)
         && ReferenceEquals(index, Index)
         && ReferenceEquals(type, Type))
            return this;
        return this with { Target = target, Index = index, Type = type };
    }
}

public partial record BoundArrayCreationExpression
{
    public BoundArrayCreationExpression Update(
        BoundType elementType,
        BoundExpression size,
        BoundType type
    )
    {
        if (ReferenceEquals(elementType, ElementType)
         && ReferenceEquals(size, Size)
         && ReferenceEquals(type, Type))
            return this;
        return this with { ElementType = elementType, Size = size, Type = type };
    }
}

public partial record BoundTupleLiteralExpression
{
    public BoundTupleLiteralExpression Update(
        IReadOnlyList<BoundExpression> elements,
        BoundType type
    )
    {
        if (ReferenceEquals(elements, Elements)
         && ReferenceEquals(type, Type))
            return this;
        return this with { Elements = elements, Type = type };
    }
}

public partial record BoundDefaultExpression
{
    public BoundDefaultExpression Update(BoundType type)
    {
        if (ReferenceEquals(type, Type)) return this;
        return this with { Type = type };
    }
}

public partial record BoundMethodGroupConversion
{
    public BoundMethodGroupConversion Update(BoundExpression? receiver)
    {
        if (ReferenceEquals(receiver, Receiver)) return this;
        return this with { Receiver = receiver };
    }
}

public partial record BoundAddressOfVariableExpression
{
    public BoundAddressOfVariableExpression Update(
        BoundExpression target,
        BoundType pointeeType
    )
    {
        if (ReferenceEquals(target, Target)
         && ReferenceEquals(pointeeType, PointeeType))
            return this;
        return this with { Target = target, PointeeType = pointeeType };
    }
}

public partial record BoundHeapAllocExpression
{
    public BoundHeapAllocExpression Update(
        BoundExpression inner,
        BoundType pointeeType
    )
    {
        if (ReferenceEquals(inner, Inner)
         && ReferenceEquals(pointeeType, PointeeType))
            return this;
        return this with { Inner = inner, PointeeType = pointeeType };
    }
}

public partial record BoundInterpolatedStringExpression
{
    public BoundInterpolatedStringExpression Update(
        IReadOnlyList<BoundInterpolationPart> parts,
        BoundType type
    )
    {
        if (ReferenceEquals(parts, Parts)
         && ReferenceEquals(type, Type))
            return this;
        return this with { Parts = parts, Type = type };
    }
}

public partial record BoundConditionalExpression
{
    public BoundConditionalExpression Update(
        BoundExpression condition,
        BoundExpression consequence,
        BoundExpression alternative,
        BoundType type
    )
    {
        if (ReferenceEquals(condition, Condition)
         && ReferenceEquals(consequence, Consequence)
         && ReferenceEquals(alternative, Alternative)
         && ReferenceEquals(type, Type))
            return this;
        return this with { Condition = condition, Consequence = consequence, Alternative = alternative, Type = type };
    }
}

public partial record BoundNullCoalescingExpression
{
    public BoundNullCoalescingExpression Update(
        BoundExpression left,
        BoundExpression right,
        BoundType type
    )
    {
        if (ReferenceEquals(left, Left)
         && ReferenceEquals(right, Right)
         && ReferenceEquals(type, Type))
            return this;
        return this with { Left = left, Right = right, Type = type };
    }
}

public partial record BoundNullConditionalAccessExpression
{
    public BoundNullConditionalAccessExpression Update(
        BoundExpression target,
        BoundType type
    )
    {
        if (ReferenceEquals(target, Target)
         && ReferenceEquals(type, Type))
            return this;
        return this with { Target = target, Type = type };
    }
}

public partial record BoundListLiteralExpression
{
    public BoundListLiteralExpression Update(
        IReadOnlyList<BoundExpression> elements,
        BoundType elementType,
        BoundType type
    )
    {
        if (ReferenceEquals(elements, Elements)
         && ReferenceEquals(elementType, ElementType)
         && ReferenceEquals(type, Type))
            return this;
        return this with { Elements = elements, ElementType = elementType, Type = type };
    }
}

public partial record BoundRangeExpression
{
    public BoundRangeExpression Update(
        BoundExpression? target,
        BoundExpression? start,
        BoundExpression? end,
        BoundType type
    )
    {
        if (ReferenceEquals(target, Target)
         && ReferenceEquals(start, Start)
         && ReferenceEquals(end, End)
         && ReferenceEquals(type, Type))
            return this;
        return this with { Target = target, Start = start, End = end, Type = type };
    }
}

public partial record BoundSpawnExpression
{
    public BoundSpawnExpression Update(BoundBlockStatement body)
    {
        if (ReferenceEquals(body, Body)) return this;
        return this with { Body = body };
    }
}

public partial record BoundChanCreationExpression
{
    public BoundChanCreationExpression Update(
        BoundType elementType,
        BoundExpression? capacity
    )
    {
        if (ReferenceEquals(elementType, ElementType)
         && ReferenceEquals(capacity, Capacity))
            return this;
        return this with { ElementType = elementType, Capacity = capacity };
    }
}

public partial record BoundDotCaseExpression
{
    public BoundDotCaseExpression Update(
        IReadOnlyList<BoundExpression> arguments,
        BoundType type
    )
    {
        if (ReferenceEquals(arguments, Arguments)
         && ReferenceEquals(type, Type))
            return this;
        return this with { Arguments = arguments, Type = type };
    }
}

public partial record BoundTryUnwrapExpression
{
    public BoundTryUnwrapExpression Update(
        BoundExpression inner,
        BoundType unwrappedType
    )
    {
        if (ReferenceEquals(inner, Inner)
         && ReferenceEquals(unwrappedType, UnwrappedType))
            return this;
        return this with { Inner = inner, UnwrappedType = unwrappedType };
    }
}

public partial record BoundWithExpression
{
    public BoundWithExpression Update(
        BoundExpression target,
        IReadOnlyList<BoundFieldInit> fields,
        BoundType type
    )
    {
        if (ReferenceEquals(target, Target)
         && ReferenceEquals(fields, Fields)
         && ReferenceEquals(type, Type))
            return this;
        return this with { Target = target, Fields = fields, Type = type };
    }
}

public partial record BoundResultCallExpression
{
    public BoundResultCallExpression Update(
        BoundExpression argument,
        BoundType okType,
        BoundType errorType
    )
    {
        if (ReferenceEquals(argument, Argument)
         && ReferenceEquals(okType, OkType)
         && ReferenceEquals(errorType, ErrorType))
            return this;
        return this with { Argument = argument, OkType = okType, ErrorType = errorType };
    }
}

public partial record BoundFunctionLiteralExpression
{
    public BoundFunctionLiteralExpression Update(
        IReadOnlyList<BoundParameter> parameters,
        BoundType returnType,
        BoundBlockStatement body,
        IReadOnlyList<BoundCapturedVariable> capturedVariables
    )
    {
        if (ReferenceEquals(parameters, Parameters)
         && ReferenceEquals(returnType, ReturnType)
         && ReferenceEquals(body, Body)
         && ReferenceEquals(capturedVariables, CapturedVariables))
            return this;
        return this with { Parameters = parameters, ReturnType = returnType, Body = body, CapturedVariables = capturedVariables };
    }
}

public partial record BoundAwaitExpression
{
    public BoundAwaitExpression Update(
        BoundExpression inner,
        BoundType resultType
    )
    {
        if (ReferenceEquals(inner, Inner)
         && ReferenceEquals(resultType, ResultType))
            return this;
        return this with { Inner = inner, ResultType = resultType };
    }
}

public partial record BoundMatchExpression
{
    public BoundMatchExpression Update(
        BoundExpression subject,
        BoundType subjectType,
        IReadOnlyList<BoundMatchExpressionArm> arms
    )
    {
        if (ReferenceEquals(subject, Subject)
         && ReferenceEquals(subjectType, SubjectType)
         && ReferenceEquals(arms, Arms))
            return this;
        return this with { Subject = subject, SubjectType = subjectType, Arms = arms };
    }
}

public partial record BoundIfExpression
{
    public BoundIfExpression Update(
        IReadOnlyList<BoundIfExpressionBranch> branches,
        IReadOnlyList<BoundStatement> elseBody,
        BoundExpression? elseValue,
        BoundType type
    )
    {
        if (ReferenceEquals(branches, Branches)
         && ReferenceEquals(elseBody, ElseBody)
         && ReferenceEquals(elseValue, ElseValue)
         && ReferenceEquals(type, Type))
            return this;
        return this with { Branches = branches, ElseBody = elseBody, ElseValue = elseValue, Type = type };
    }
}
