// ============================================================================
// BoundTreeRewriter — default identity rewriter.
//
// GENERATED by bound-nodes-gen.py from bound-nodes.schema.json.
// DO NOT EDIT by hand — edit the schema and re-run the generator.
//
// A BoundTree → BoundTree transform pass derives from this class and overrides
// only the nodes it needs to rewrite. The default for every node is to recurse
// into children and, if ANYTHING changed, return a `with`-clone of the parent;
// if nothing changed, return the same reference (no allocation).
//
// That "changed?" check is strict reference equality (ReferenceEquals), which
// is correct because BoundNode subtypes override Equals to reference-based
// identity (preventing structural-record cycle through BoundType.Symbol).
//
// Lowering passes MUST derive from this rather than writing ad-hoc walks.
// The contract: every derived class must call base.Rewrite* for any child it
// does not explicitly replace — omitting a child corrupts the tree.
//
// FEATURE nodes: a post-lowering assertion pass (BoundFeatureAssert, in the
// Lowering library) derives from this and overrides every FEATURE Visit to
// throw InvalidOperationException("FEATURE node <T> reached CodeGen").
// ============================================================================

namespace Esharp.BoundTree;

public abstract class BoundTreeRewriter
{

    // ---- Entry points ----

    public virtual BoundStatement RewriteStatement(BoundStatement stmt) => stmt switch
    {
        // CORE
        BoundBlockStatement _n                 => RewriteBlockStatement(_n),
        BoundVariableDeclaration _n            => RewriteVariableDeclaration(_n),
        BoundAssignment _n                     => RewriteAssignment(_n),
        BoundIfStatement _n                    => RewriteIfStatement(_n),
        BoundWhileStatement _n                 => RewriteWhileStatement(_n),
        BoundReturnStatement _n                => RewriteReturnStatement(_n),
        BoundBreakStatement _n               => _n,
        BoundContinueStatement _n               => _n,
        BoundLabelStatement _n               => _n,
        BoundGotoStatement _n               => _n,
        BoundExpressionStatement _n            => RewriteExpressionStatement(_n),
        BoundScopedMutCall _n                  => RewriteScopedMutCall(_n),
        BoundTryStatement _n                   => RewriteTryStatement(_n),
        BoundThrowStatement _n                 => RewriteThrowStatement(_n),
        BoundConstStatement _n                 => RewriteConstStatement(_n),

        // FEATURE
        BoundRaiseStatement _n                 => RewriteRaiseStatement(_n),
        BoundLetGuard _n                       => RewriteLetGuard(_n),
        BoundForEachStatement _n               => RewriteForEachStatement(_n),
        BoundMatchStatement _n                 => RewriteMatchStatement(_n),
        BoundDeferStatement _n                 => RewriteDeferStatement(_n),
        BoundAsyncLetStatement _n              => RewriteAsyncLetStatement(_n),
        BoundYieldStatement _n                 => RewriteYieldStatement(_n),
        BoundSelectStatement _n                => RewriteSelectStatement(_n),
        BoundCompoundAssignment _n             => RewriteCompoundAssignment(_n),

        _ => stmt,
    };

    public virtual BoundExpression RewriteExpression(BoundExpression expr) => expr switch
    {
        // CORE
        BoundErrorExpression _n               => _n,
        BoundLiteralExpression _n               => _n,
        BoundNameExpression _n                 => RewriteNameExpression(_n),
        BoundUnaryExpression _n                => RewriteUnaryExpression(_n),
        BoundBinaryExpression _n               => RewriteBinaryExpression(_n),
        BoundMemberAccessExpression _n         => RewriteMemberAccessExpression(_n),
        BoundConversion _n                     => RewriteConversion(_n),
        BoundTypeTestExpression _n             => RewriteTypeTestExpression(_n),
        BoundCallExpression _n                 => RewriteCallExpression(_n),
        BoundObjectCreationExpression _n       => RewriteObjectCreationExpression(_n),
        BoundIndexExpression _n                => RewriteIndexExpression(_n),
        BoundArrayCreationExpression _n        => RewriteArrayCreationExpression(_n),
        BoundStackAllocExpression _n           => RewriteStackAllocExpression(_n),
        BoundTupleLiteralExpression _n         => RewriteTupleLiteralExpression(_n),
        BoundDefaultExpression _n               => _n,
        BoundOutArgumentExpression _n               => _n,
        BoundAddressOfExpression _n               => _n,
        BoundMethodGroupConversion _n          => RewriteMethodGroupConversion(_n),
        BoundAddressOfVariableExpression _n    => RewriteAddressOfVariableExpression(_n),
        BoundHeapAllocExpression _n            => RewriteHeapAllocExpression(_n),
        BoundInterpolatedStringExpression _n   => RewriteInterpolatedStringExpression(_n),
        BoundConditionalExpression _n          => RewriteConditionalExpression(_n),

        // FEATURE
        BoundNullCoalescingExpression _n       => RewriteNullCoalescingExpression(_n),
        BoundNullConditionalAccessExpression _n => RewriteNullConditionalAccessExpression(_n),
        BoundListLiteralExpression _n          => RewriteListLiteralExpression(_n),
        BoundRangeExpression _n                => RewriteRangeExpression(_n),
        BoundSpawnExpression _n                => RewriteSpawnExpression(_n),
        BoundChanCreationExpression _n         => RewriteChanCreationExpression(_n),
        BoundDotCaseExpression _n              => RewriteDotCaseExpression(_n),
        BoundTryUnwrapExpression _n            => RewriteTryUnwrapExpression(_n),
        BoundWithExpression _n                 => RewriteWithExpression(_n),
        BoundResultCallExpression _n           => RewriteResultCallExpression(_n),
        BoundFunctionLiteralExpression _n      => RewriteFunctionLiteralExpression(_n),
        BoundAwaitExpression _n                => RewriteAwaitExpression(_n),
        BoundMatchExpression _n                => RewriteMatchExpression(_n),
        BoundIfExpression _n                   => RewriteIfExpression(_n),

        _ => expr,
    };

    // ---- Helpers ----

    protected IReadOnlyList<BoundStatement> RewriteStatements(IReadOnlyList<BoundStatement> list)
    {
        List<BoundStatement>? result = null;
        for (int i = 0; i < list.Count; i++)
        {
            var old = list[i];
            var @new = RewriteStatement(old);
            if (!ReferenceEquals(old, @new))
            {
                result ??= [.. list.Take(i)];
            }
            result?.Add(@new);
        }
        return result is null ? list : result;
    }

    protected IReadOnlyList<BoundExpression> RewriteExpressions(IReadOnlyList<BoundExpression> list)
    {
        List<BoundExpression>? result = null;
        for (int i = 0; i < list.Count; i++)
        {
            var old = list[i];
            var @new = RewriteExpression(old);
            if (!ReferenceEquals(old, @new))
            {
                result ??= [.. list.Take(i)];
            }
            result?.Add(@new);
        }
        return result is null ? list : result;
    }

    protected IReadOnlyList<BoundFieldInit> RewriteFieldInits(IReadOnlyList<BoundFieldInit> list)
    {
        List<BoundFieldInit>? result = null;
        for (int i = 0; i < list.Count; i++)
        {
            var old = list[i];
            var @new = RewriteExpression(old.Value);
            if (!ReferenceEquals(old.Value, @new))
            {
                result ??= [.. list.Take(i)];
            }
            result?.Add(result is null ? old : old with { Value = @new });
        }
        return result is null ? list : result;
    }

    protected BoundBlockStatement RewriteBlock(BoundBlockStatement block)
    {
        var stmts = RewriteStatements(block.Statements);
        return ReferenceEquals(stmts, block.Statements) ? block : block with { Statements = stmts };
    }

    // ---- CORE statements ----

    protected virtual BoundStatement RewriteBlockStatement(BoundBlockStatement node)
    {
        var statements = RewriteStatements(node.Statements);
        if (ReferenceEquals(statements, node.Statements)) return node;
        return node with { Statements = statements };
    }

    protected virtual BoundStatement RewriteVariableDeclaration(BoundVariableDeclaration node)
    {
        var initializer = RewriteExpression(node.Initializer);
        if (ReferenceEquals(initializer, node.Initializer)) return node;
        return node with { Initializer = initializer };
    }

    protected virtual BoundStatement RewriteAssignment(BoundAssignment node)
    {
        var target = RewriteExpression(node.Target);
        var value = RewriteExpression(node.Value);
        bool _same = ReferenceEquals(target, node.Target)
                  && ReferenceEquals(value, node.Value);
        if (_same) return node;
        return node with { Target = target, Value = value };
    }

    protected virtual BoundStatement RewriteIfStatement(BoundIfStatement node)
    {
        var condition = RewriteExpression(node.Condition);
        var then = RewriteStatement(node.Then);
        var @else = node.Else is {} __Else ? RewriteStatement(__Else) : null;
        bool _same = ReferenceEquals(condition, node.Condition)
                  && ReferenceEquals(then, node.Then)
                  && ReferenceEquals(@else, node.Else);
        if (_same) return node;
        return node with { Condition = condition, Then = then, Else = @else };
    }

    protected virtual BoundStatement RewriteWhileStatement(BoundWhileStatement node)
    {
        var condition = RewriteExpression(node.Condition);
        var body = RewriteStatement(node.Body);
        bool _same = ReferenceEquals(condition, node.Condition)
                  && ReferenceEquals(body, node.Body);
        if (_same) return node;
        return node with { Condition = condition, Body = body };
    }

    protected virtual BoundStatement RewriteReturnStatement(BoundReturnStatement node)
    {
        var expression = node.Expression is {} __Expression ? RewriteExpression(__Expression) : null;
        if (ReferenceEquals(expression, node.Expression)) return node;
        return node with { Expression = expression };
    }

    protected virtual BoundStatement RewriteExpressionStatement(BoundExpressionStatement node)
    {
        var expression = RewriteExpression(node.Expression);
        if (ReferenceEquals(expression, node.Expression)) return node;
        return node with { Expression = expression };
    }

    protected virtual BoundStatement RewriteScopedMutCall(BoundScopedMutCall node)
    {
        var receiver = RewriteExpression(node.Receiver);
        var call = (BoundCallExpression)RewriteExpression(node.Call);
        bool _same = ReferenceEquals(receiver, node.Receiver)
                  && ReferenceEquals(call, node.Call);
        if (_same) return node;
        return node with { Receiver = receiver, Call = call };
    }

    protected virtual BoundStatement RewriteTryStatement(BoundTryStatement node)
    {
        var body = RewriteBlock(node.Body);
        List<BoundCatchClause>? catches = null;
        for (int i = 0; i < node.Catches.Count; i++)
        {
            var c = node.Catches[i];
            var newBody  = RewriteBlock(c.Body);
            var newGuard = c.Guard is { } g ? RewriteExpression(g) : null;
            bool catchSame = ReferenceEquals(newBody, c.Body) && ReferenceEquals(newGuard, c.Guard);
            if (!catchSame)
            {
                catches ??= [.. node.Catches.Take(i)];
                catches.Add(c with { Body = newBody, Guard = newGuard });
            }
            else catches?.Add(c);
        }
        IReadOnlyList<BoundCatchClause> finalCatches = catches ?? node.Catches;
        bool same = ReferenceEquals(body, node.Body) && catches is null;
        return same ? node : node with { Body = body, Catches = finalCatches };
    }

    protected virtual BoundStatement RewriteThrowStatement(BoundThrowStatement node)
    {
        var expression = node.Expression is {} __Expression ? RewriteExpression(__Expression) : null;
        if (ReferenceEquals(expression, node.Expression)) return node;
        return node with { Expression = expression };
    }

    protected virtual BoundStatement RewriteConstStatement(BoundConstStatement node)
    {
        var value = RewriteExpression(node.Value);
        if (ReferenceEquals(value, node.Value)) return node;
        return node with { Value = value };
    }

    // ---- FEATURE statements ----

    protected virtual BoundStatement RewriteRaiseStatement(BoundRaiseStatement node)
    {
        var arguments = RewriteExpressions(node.Arguments);
        if (ReferenceEquals(arguments, node.Arguments)) return node;
        return node with { Arguments = arguments };
    }

    protected virtual BoundStatement RewriteLetGuard(BoundLetGuard node)
    {
        var initializer = RewriteExpression(node.Initializer);
        var elseBody = RewriteBlock(node.ElseBody);
        bool _same = ReferenceEquals(initializer, node.Initializer)
                  && ReferenceEquals(elseBody, node.ElseBody);
        if (_same) return node;
        return node with { Initializer = initializer, ElseBody = elseBody };
    }

    protected virtual BoundStatement RewriteForEachStatement(BoundForEachStatement node)
    {
        var collection = RewriteExpression(node.Collection);
        var body = RewriteStatement(node.Body);
        bool _same = ReferenceEquals(collection, node.Collection)
                  && ReferenceEquals(body, node.Body);
        if (_same) return node;
        return node with { Collection = collection, Body = body };
    }

    protected virtual BoundStatement RewriteMatchStatement(BoundMatchStatement node)
    {
        var subject = RewriteExpression(node.Subject);
        List<BoundMatchArm>? arms = null;
        for (int i = 0; i < node.Arms.Count; i++)
        {
            var arm = node.Arms[i];
            var newGuard = arm.Guard is { } g ? RewriteExpression(g) : null;
            var newBody  = RewriteBlock(arm.Body);
            bool armSame = ReferenceEquals(newGuard, arm.Guard) && ReferenceEquals(newBody, arm.Body);
            if (!armSame)
            {
                arms ??= [.. node.Arms.Take(i)];
                arms.Add(arm with { Guard = newGuard, Body = newBody });
            }
            else arms?.Add(arm);
        }
        bool same = ReferenceEquals(subject, node.Subject) && arms is null;
        return same ? node : node with { Subject = subject, Arms = arms ?? node.Arms };
    }

    protected virtual BoundStatement RewriteDeferStatement(BoundDeferStatement node)
    {
        var body = RewriteBlock(node.Body);
        if (ReferenceEquals(body, node.Body)) return node;
        return node with { Body = body };
    }

    protected virtual BoundStatement RewriteAsyncLetStatement(BoundAsyncLetStatement node)
    {
        var initializer = RewriteExpression(node.Initializer);
        if (ReferenceEquals(initializer, node.Initializer)) return node;
        return node with { Initializer = initializer };
    }

    protected virtual BoundStatement RewriteYieldStatement(BoundYieldStatement node)
    {
        var value = RewriteExpression(node.Value);
        if (ReferenceEquals(value, node.Value)) return node;
        return node with { Value = value };
    }

    protected virtual BoundStatement RewriteSelectStatement(BoundSelectStatement node)
    {
        List<BoundSelectArm>? arms = null;
        for (int i = 0; i < node.Arms.Count; i++)
        {
            var arm  = node.Arms[i];
            var ch   = arm.Channel is { } c ? RewriteExpression(c) : null;
            var val  = arm.Value   is { } v ? RewriteExpression(v) : null;
            var body = RewriteBlock(arm.Body);
            bool same = ReferenceEquals(ch, arm.Channel) && ReferenceEquals(val, arm.Value) && ReferenceEquals(body, arm.Body);
            if (!same)
            {
                arms ??= [.. node.Arms.Take(i)];
                arms.Add(arm with { Channel = ch, Value = val, Body = body });
            }
            else arms?.Add(arm);
        }
        return arms is null ? node : node with { Arms = arms };
    }

    protected virtual BoundStatement RewriteCompoundAssignment(BoundCompoundAssignment node)
    {
        var target = RewriteExpression(node.Target);
        var value = RewriteExpression(node.Value);
        bool _same = ReferenceEquals(target, node.Target)
                  && ReferenceEquals(value, node.Value);
        if (_same) return node;
        return node with { Target = target, Value = value };
    }

    // ---- CORE expressions ----

    protected virtual BoundExpression RewriteNameExpression(BoundNameExpression node)
    {
        return node;
    }

    protected virtual BoundExpression RewriteUnaryExpression(BoundUnaryExpression node)
    {
        var operand = RewriteExpression(node.Operand);
        if (ReferenceEquals(operand, node.Operand)) return node;
        return node with { Operand = operand };
    }

    protected virtual BoundExpression RewriteBinaryExpression(BoundBinaryExpression node)
    {
        var left = RewriteExpression(node.Left);
        var right = RewriteExpression(node.Right);
        bool _same = ReferenceEquals(left, node.Left)
                  && ReferenceEquals(right, node.Right);
        if (_same) return node;
        return node with { Left = left, Right = right };
    }

    protected virtual BoundExpression RewriteMemberAccessExpression(BoundMemberAccessExpression node)
    {
        var target = RewriteExpression(node.Target);
        if (ReferenceEquals(target, node.Target)) return node;
        return node with { Target = target };
    }

    protected virtual BoundExpression RewriteConversion(BoundConversion node)
    {
        var operand = RewriteExpression(node.Operand);
        if (ReferenceEquals(operand, node.Operand)) return node;
        return node with { Operand = operand };
    }

    protected virtual BoundExpression RewriteTypeTestExpression(BoundTypeTestExpression node)
    {
        var operand = RewriteExpression(node.Operand);
        if (ReferenceEquals(operand, node.Operand)) return node;
        return node with { Operand = operand };
    }

    protected virtual BoundExpression RewriteCallExpression(BoundCallExpression node)
    {
        var target = RewriteExpression(node.Target);
        var arguments = RewriteExpressions(node.Arguments);
        bool _same = ReferenceEquals(target, node.Target)
                  && ReferenceEquals(arguments, node.Arguments);
        if (_same) return node;
        return node with { Target = target, Arguments = arguments };
    }

    protected virtual BoundExpression RewriteObjectCreationExpression(BoundObjectCreationExpression node)
    {
        var fields = RewriteFieldInits(node.Fields);
        var constructorArguments = RewriteExpressions(node.ConstructorArguments);
        bool _same = ReferenceEquals(fields, node.Fields)
                  && ReferenceEquals(constructorArguments, node.ConstructorArguments);
        if (_same) return node;
        return node with { Fields = fields, ConstructorArguments = constructorArguments };
    }

    protected virtual BoundExpression RewriteIndexExpression(BoundIndexExpression node)
    {
        var target = RewriteExpression(node.Target);
        var index = RewriteExpression(node.Index);
        bool _same = ReferenceEquals(target, node.Target)
                  && ReferenceEquals(index, node.Index);
        if (_same) return node;
        return node with { Target = target, Index = index };
    }

    protected virtual BoundExpression RewriteArrayCreationExpression(BoundArrayCreationExpression node)
    {
        var size = RewriteExpression(node.Size);
        if (ReferenceEquals(size, node.Size)) return node;
        return node with { Size = size };
    }

    protected virtual BoundExpression RewriteStackAllocExpression(BoundStackAllocExpression node)
    {
        var size = RewriteExpression(node.Size);
        if (ReferenceEquals(size, node.Size)) return node;
        return node with { Size = size };
    }

    protected virtual BoundExpression RewriteTupleLiteralExpression(BoundTupleLiteralExpression node)
    {
        var elements = RewriteExpressions(node.Elements);
        if (ReferenceEquals(elements, node.Elements)) return node;
        return node with { Elements = elements };
    }

    protected virtual BoundExpression RewriteMethodGroupConversion(BoundMethodGroupConversion node)
    {
        var receiver = node.Receiver is {} __Receiver ? RewriteExpression(__Receiver) : null;
        if (ReferenceEquals(receiver, node.Receiver)) return node;
        return node with { Receiver = receiver };
    }

    protected virtual BoundExpression RewriteAddressOfVariableExpression(BoundAddressOfVariableExpression node)
    {
        var target = RewriteExpression(node.Target);
        if (ReferenceEquals(target, node.Target)) return node;
        return node with { Target = target };
    }

    protected virtual BoundExpression RewriteHeapAllocExpression(BoundHeapAllocExpression node)
    {
        var inner = RewriteExpression(node.Inner);
        if (ReferenceEquals(inner, node.Inner)) return node;
        return node with { Inner = inner };
    }

    protected virtual BoundExpression RewriteInterpolatedStringExpression(BoundInterpolatedStringExpression node)
    {
        List<BoundInterpolationPart>? parts = null;
        for (int i = 0; i < node.Parts.Count; i++)
        {
            var p = node.Parts[i];
            if (p.Expr is null) { parts?.Add(p); continue; }
            var newExpr = RewriteExpression(p.Expr);
            if (!ReferenceEquals(newExpr, p.Expr))
            {
                parts ??= [.. node.Parts.Take(i)];
                parts.Add(p with { Expr = newExpr });
            }
            else parts?.Add(p);
        }
        return parts is null ? node : node with { Parts = parts };
    }

    protected virtual BoundExpression RewriteConditionalExpression(BoundConditionalExpression node)
    {
        var condition = RewriteExpression(node.Condition);
        var consequence = RewriteExpression(node.Consequence);
        var alternative = RewriteExpression(node.Alternative);
        bool _same = ReferenceEquals(condition, node.Condition)
                  && ReferenceEquals(consequence, node.Consequence)
                  && ReferenceEquals(alternative, node.Alternative);
        if (_same) return node;
        return node with { Condition = condition, Consequence = consequence, Alternative = alternative };
    }

    // ---- FEATURE expressions ----

    protected virtual BoundExpression RewriteNullCoalescingExpression(BoundNullCoalescingExpression node)
    {
        var left = RewriteExpression(node.Left);
        var right = RewriteExpression(node.Right);
        bool _same = ReferenceEquals(left, node.Left)
                  && ReferenceEquals(right, node.Right);
        if (_same) return node;
        return node with { Left = left, Right = right };
    }

    protected virtual BoundExpression RewriteNullConditionalAccessExpression(BoundNullConditionalAccessExpression node)
    {
        var target = RewriteExpression(node.Target);
        if (ReferenceEquals(target, node.Target)) return node;
        return node with { Target = target };
    }

    protected virtual BoundExpression RewriteListLiteralExpression(BoundListLiteralExpression node)
    {
        var elements = RewriteExpressions(node.Elements);
        if (ReferenceEquals(elements, node.Elements)) return node;
        return node with { Elements = elements };
    }

    protected virtual BoundExpression RewriteRangeExpression(BoundRangeExpression node)
    {
        var target = node.Target is {} __Target ? RewriteExpression(__Target) : null;
        var start = node.Start is {} __Start ? RewriteExpression(__Start) : null;
        var end = node.End is {} __End ? RewriteExpression(__End) : null;
        bool _same = ReferenceEquals(target, node.Target)
                  && ReferenceEquals(start, node.Start)
                  && ReferenceEquals(end, node.End);
        if (_same) return node;
        return node with { Target = target, Start = start, End = end };
    }

    protected virtual BoundExpression RewriteSpawnExpression(BoundSpawnExpression node)
    {
        var body = RewriteBlock(node.Body);
        if (ReferenceEquals(body, node.Body)) return node;
        return node with { Body = body };
    }

    protected virtual BoundExpression RewriteChanCreationExpression(BoundChanCreationExpression node)
    {
        var capacity = node.Capacity is {} __Capacity ? RewriteExpression(__Capacity) : null;
        if (ReferenceEquals(capacity, node.Capacity)) return node;
        return node with { Capacity = capacity };
    }

    protected virtual BoundExpression RewriteDotCaseExpression(BoundDotCaseExpression node)
    {
        var arguments = RewriteExpressions(node.Arguments);
        if (ReferenceEquals(arguments, node.Arguments)) return node;
        return node with { Arguments = arguments };
    }

    protected virtual BoundExpression RewriteTryUnwrapExpression(BoundTryUnwrapExpression node)
    {
        var inner = RewriteExpression(node.Inner);
        if (ReferenceEquals(inner, node.Inner)) return node;
        return node with { Inner = inner };
    }

    protected virtual BoundExpression RewriteWithExpression(BoundWithExpression node)
    {
        var target = RewriteExpression(node.Target);
        var fields = RewriteFieldInits(node.Fields);
        bool _same = ReferenceEquals(target, node.Target)
                  && ReferenceEquals(fields, node.Fields);
        if (_same) return node;
        return node with { Target = target, Fields = fields };
    }

    protected virtual BoundExpression RewriteResultCallExpression(BoundResultCallExpression node)
    {
        var argument = RewriteExpression(node.Argument);
        if (ReferenceEquals(argument, node.Argument)) return node;
        return node with { Argument = argument };
    }

    protected virtual BoundExpression RewriteFunctionLiteralExpression(BoundFunctionLiteralExpression node)
    {
        var body = RewriteBlock(node.Body);
        if (ReferenceEquals(body, node.Body)) return node;
        return node with { Body = body };
    }

    protected virtual BoundExpression RewriteAwaitExpression(BoundAwaitExpression node)
    {
        var inner = RewriteExpression(node.Inner);
        if (ReferenceEquals(inner, node.Inner)) return node;
        return node with { Inner = inner };
    }

    protected virtual BoundExpression RewriteMatchExpression(BoundMatchExpression node)
    {
        var subject = RewriteExpression(node.Subject);
        List<BoundMatchExpressionArm>? arms = null;
        for (int i = 0; i < node.Arms.Count; i++)
        {
            var arm = node.Arms[i];
            var newGuard = arm.Guard is { } g ? RewriteExpression(g) : null;
            var newVal   = RewriteExpression(arm.Value);
            bool armSame = ReferenceEquals(newGuard, arm.Guard) && ReferenceEquals(newVal, arm.Value);
            if (!armSame)
            {
                arms ??= [.. node.Arms.Take(i)];
                arms.Add(arm with { Guard = newGuard, Value = newVal });
            }
            else arms?.Add(arm);
        }
        bool same = ReferenceEquals(subject, node.Subject) && arms is null;
        return same ? node : node with { Subject = subject, Arms = arms ?? node.Arms };
    }

    protected virtual BoundExpression RewriteIfExpression(BoundIfExpression node)
    {
        List<BoundIfExpressionBranch>? branches = null;
        for (int i = 0; i < node.Branches.Count; i++)
        {
            var b     = node.Branches[i];
            var cond  = RewriteExpression(b.Condition);
            var stmts = RewriteStatements(b.Body);
            var val   = b.Value is { } v ? RewriteExpression(v) : null;
            bool same = ReferenceEquals(cond, b.Condition)
                     && ReferenceEquals(stmts, b.Body)
                     && ReferenceEquals(val, b.Value);
            if (!same)
            {
                branches ??= [.. node.Branches.Take(i)];
                branches.Add(b with { Condition = cond, Body = stmts, Value = val });
            }
            else branches?.Add(b);
        }
        var elseStmts = RewriteStatements(node.ElseBody);
        var elseVal   = node.ElseValue is { } ev ? RewriteExpression(ev) : null;
        bool nodeSame = branches is null
                     && ReferenceEquals(elseStmts, node.ElseBody)
                     && ReferenceEquals(elseVal,   node.ElseValue);
        return nodeSame
            ? node
            : node with { Branches = branches ?? node.Branches, ElseBody = elseStmts, ElseValue = elseVal };
    }

}
