// ============================================================================
// BoundTreeVisitor — abstract visitor + concrete no-op default visitor.
//
// GENERATED by bound-nodes-gen.py from bound-nodes.schema.json.
// DO NOT EDIT by hand — edit the schema and re-run the generator.
//
// Usage:
//   Derive from BoundTreeVisitor<T> for a fold (each Visit returns T).
//   Derive from BoundTreeVisitor for a side-effect walk (returns void).
//
// CORE and FEATURE nodes are both listed; a Lowering pass visitor can assert
// that no FEATURE nodes are present by overriding the FEATURE visits to throw.
// ============================================================================

namespace Esharp.BoundTree;


// ---------------------------------------------------------------------------
// Void visitor (side-effect walk)
// ---------------------------------------------------------------------------

public abstract class BoundTreeVisitor
{
    // Central dispatch. Subclasses rarely override this — override the
    // typed Visit methods below instead.
    public virtual void VisitNode(BoundNode node)
    {
        switch (node)
        {

            // Top-level
            case BoundCompilationUnit _n:                   VisitCompilationUnit(_n); break;

            // Members
            case BoundFunctionDeclaration _n:               VisitFunctionDeclaration(_n); break;
            case BoundDataDeclaration _n:                   VisitDataDeclaration(_n); break;
            case BoundInitDeclaration _n:                   VisitInitDeclaration(_n); break;
            case BoundNamespaceInitDeclaration _n:          VisitNamespaceInitDeclaration(_n); break;
            case BoundNamespaceStateDeclaration _n:         VisitNamespaceStateDeclaration(_n); break;
            case BoundInterfaceDeclaration _n:              VisitInterfaceDeclaration(_n); break;
            case BoundDelegateDeclaration _n:               VisitDelegateDeclaration(_n); break;
            case BoundStaticFuncDeclaration _n:             VisitStaticFuncDeclaration(_n); break;
            case BoundConstDeclaration _n:                  VisitConstDeclaration(_n); break;
            case BoundChoiceDeclaration _n:                 VisitChoiceDeclaration(_n); break;
            case BoundEnumDeclaration _n:                   VisitEnumDeclaration(_n); break;

            // Statements — CORE
            case BoundBlockStatement _n:                    VisitBlockStatement(_n); break;
            case BoundVariableDeclaration _n:               VisitVariableDeclaration(_n); break;
            case BoundAssignment _n:                        VisitAssignment(_n); break;
            case BoundIfStatement _n:                       VisitIfStatement(_n); break;
            case BoundWhileStatement _n:                    VisitWhileStatement(_n); break;
            case BoundReturnStatement _n:                   VisitReturnStatement(_n); break;
            case BoundBreakStatement _n:                    VisitBreakStatement(_n); break;
            case BoundContinueStatement _n:                 VisitContinueStatement(_n); break;
            case BoundLabelStatement _n:                    VisitLabelStatement(_n); break;
            case BoundGotoStatement _n:                     VisitGotoStatement(_n); break;
            case BoundExpressionStatement _n:               VisitExpressionStatement(_n); break;
            case BoundScopedMutCall _n:                     VisitScopedMutCall(_n); break;
            case BoundTryStatement _n:                      VisitTryStatement(_n); break;
            case BoundThrowStatement _n:                    VisitThrowStatement(_n); break;
            case BoundConstStatement _n:                    VisitConstStatement(_n); break;

            // Statements — FEATURE
            case BoundRaiseStatement _n:                    VisitRaiseStatement(_n); break;
            case BoundLetGuard _n:                          VisitLetGuard(_n); break;
            case BoundForEachStatement _n:                  VisitForEachStatement(_n); break;
            case BoundMatchStatement _n:                    VisitMatchStatement(_n); break;
            case BoundDeferStatement _n:                    VisitDeferStatement(_n); break;
            case BoundAsyncLetStatement _n:                 VisitAsyncLetStatement(_n); break;
            case BoundYieldStatement _n:                    VisitYieldStatement(_n); break;
            case BoundSelectStatement _n:                   VisitSelectStatement(_n); break;
            case BoundCompoundAssignment _n:                VisitCompoundAssignment(_n); break;

            // Expressions — CORE
            case BoundErrorExpression _n:                   VisitErrorExpression(_n); break;
            case BoundLiteralExpression _n:                 VisitLiteralExpression(_n); break;
            case BoundNameExpression _n:                    VisitNameExpression(_n); break;
            case BoundUnaryExpression _n:                   VisitUnaryExpression(_n); break;
            case BoundBinaryExpression _n:                  VisitBinaryExpression(_n); break;
            case BoundMemberAccessExpression _n:            VisitMemberAccessExpression(_n); break;
            case BoundConversion _n:                        VisitConversion(_n); break;
            case BoundTypeTestExpression _n:                VisitTypeTestExpression(_n); break;
            case BoundCallExpression _n:                    VisitCallExpression(_n); break;
            case BoundObjectCreationExpression _n:          VisitObjectCreationExpression(_n); break;
            case BoundIndexExpression _n:                   VisitIndexExpression(_n); break;
            case BoundArrayCreationExpression _n:           VisitArrayCreationExpression(_n); break;
            case BoundStackAllocExpression _n:              VisitStackAllocExpression(_n); break;
            case BoundTupleLiteralExpression _n:            VisitTupleLiteralExpression(_n); break;
            case BoundDefaultExpression _n:                 VisitDefaultExpression(_n); break;
            case BoundOutArgumentExpression _n:             VisitOutArgumentExpression(_n); break;
            case BoundAddressOfExpression _n:               VisitAddressOfExpression(_n); break;
            case BoundMethodGroupConversion _n:             VisitMethodGroupConversion(_n); break;
            case BoundAddressOfVariableExpression _n:       VisitAddressOfVariableExpression(_n); break;
            case BoundHeapAllocExpression _n:               VisitHeapAllocExpression(_n); break;
            case BoundInterpolatedStringExpression _n:      VisitInterpolatedStringExpression(_n); break;
            case BoundConditionalExpression _n:             VisitConditionalExpression(_n); break;

            // Expressions — FEATURE
            case BoundNullCoalescingExpression _n:          VisitNullCoalescingExpression(_n); break;
            case BoundNullConditionalAccessExpression _n:   VisitNullConditionalAccessExpression(_n); break;
            case BoundListLiteralExpression _n:             VisitListLiteralExpression(_n); break;
            case BoundRangeExpression _n:                   VisitRangeExpression(_n); break;
            case BoundSpawnExpression _n:                   VisitSpawnExpression(_n); break;
            case BoundChanCreationExpression _n:            VisitChanCreationExpression(_n); break;
            case BoundDotCaseExpression _n:                 VisitDotCaseExpression(_n); break;
            case BoundTryUnwrapExpression _n:               VisitTryUnwrapExpression(_n); break;
            case BoundWithExpression _n:                    VisitWithExpression(_n); break;
            case BoundResultCallExpression _n:              VisitResultCallExpression(_n); break;
            case BoundFunctionLiteralExpression _n:         VisitFunctionLiteralExpression(_n); break;
            case BoundAwaitExpression _n:                   VisitAwaitExpression(_n); break;
            case BoundMatchExpression _n:                   VisitMatchExpression(_n); break;
            case BoundIfExpression _n:                      VisitIfExpression(_n); break;

            default:
                VisitUnknown(node);
                break;
        }
    }

    // Called for node types not covered above — future-proofing; override to throw
    // if strict exhaustion is required.
    protected virtual void VisitUnknown(BoundNode node) { }

    // ---- Top-level ----
    protected virtual void VisitCompilationUnit(BoundCompilationUnit node)
    {
        foreach (var m in node.Members)
            VisitMember(m);
    }

    protected virtual void VisitMember(BoundMember member) => VisitNode(member);

    // ---- Members ----
    protected virtual void VisitFunctionDeclaration(BoundFunctionDeclaration node)
    {
    VisitBlockStatement(node.Body);
    }

    protected virtual void VisitDataDeclaration(BoundDataDeclaration node)
    {
    foreach (var _m in node.InstanceMethods) VisitFunctionDeclaration(_m);
    if (node.Inits is {} _i_list)
        foreach (var _i in _i_list) VisitInitDeclaration(_i);
    }

    protected virtual void VisitInitDeclaration(BoundInitDeclaration node)
    {
    VisitBlockStatement(node.Body);
    if (node.BaseArguments is {} _b_list)
        foreach (var _e in _b_list) VisitExpression(_e);
    if (node.ThisArguments is {} _t_list)
        foreach (var _e in _t_list) VisitExpression(_e);
    }

    protected virtual void VisitNamespaceInitDeclaration(BoundNamespaceInitDeclaration node)
    {
    VisitBlockStatement(node.Body);
    }

    protected virtual void VisitNamespaceStateDeclaration(BoundNamespaceStateDeclaration node)
    {
    if (node.ComputedGetter is {} _c) VisitExpression(_c);
    if (node.SetterBody is {} _s) VisitExpression(_s);
    }

    protected virtual void VisitInterfaceDeclaration(BoundInterfaceDeclaration node) { }

    protected virtual void VisitDelegateDeclaration(BoundDelegateDeclaration node) { }

    protected virtual void VisitStaticFuncDeclaration(BoundStaticFuncDeclaration node)
    {
    foreach (var _m in node.Functions) VisitFunctionDeclaration(_m);
    }

    protected virtual void VisitConstDeclaration(BoundConstDeclaration node)
    {
    VisitExpression(node.Value);
    }

    protected virtual void VisitChoiceDeclaration(BoundChoiceDeclaration node) { }

    protected virtual void VisitEnumDeclaration(BoundEnumDeclaration node) { }

    // ---- Statements ----
    protected virtual void VisitStatement(BoundStatement stmt) => VisitNode(stmt);

    // CORE
    protected virtual void VisitBlockStatement(BoundBlockStatement node)
    {
    foreach (var _s in node.Statements) VisitStatement(_s);
    }

    protected virtual void VisitVariableDeclaration(BoundVariableDeclaration node)
    {
    VisitExpression(node.Initializer);
    }

    protected virtual void VisitAssignment(BoundAssignment node)
    {
    VisitExpression(node.Target);
    VisitExpression(node.Value);
    }

    protected virtual void VisitIfStatement(BoundIfStatement node)
    {
    VisitExpression(node.Condition);
    VisitStatement(node.Then);
    if (node.Else is {} _e) VisitStatement(_e);
    }

    protected virtual void VisitWhileStatement(BoundWhileStatement node)
    {
    VisitExpression(node.Condition);
    VisitStatement(node.Body);
    }

    protected virtual void VisitReturnStatement(BoundReturnStatement node)
    {
    if (node.Expression is {} _e) VisitExpression(_e);
    }

    protected virtual void VisitBreakStatement(BoundBreakStatement node) { }

    protected virtual void VisitContinueStatement(BoundContinueStatement node) { }

    protected virtual void VisitLabelStatement(BoundLabelStatement node) { }

    protected virtual void VisitGotoStatement(BoundGotoStatement node) { }

    protected virtual void VisitExpressionStatement(BoundExpressionStatement node)
    {
    VisitExpression(node.Expression);
    }

    protected virtual void VisitScopedMutCall(BoundScopedMutCall node)
    {
    VisitExpression(node.Receiver);
    VisitExpression(node.Call);
    }

    protected virtual void VisitTryStatement(BoundTryStatement node)
    {
    VisitBlockStatement(node.Body);
    VisitBlockStatement(node.Body);
    foreach (var _c in node.Catches)
    {
        VisitBlockStatement(_c.Body);
        if (_c.Guard is {} _g) VisitExpression(_g);
    }
    }

    protected virtual void VisitThrowStatement(BoundThrowStatement node)
    {
    if (node.Expression is {} _e) VisitExpression(_e);
    }

    protected virtual void VisitConstStatement(BoundConstStatement node)
    {
    VisitExpression(node.Value);
    }

    // FEATURE
    protected virtual void VisitRaiseStatement(BoundRaiseStatement node)
    {
    foreach (var _e in node.Arguments) VisitExpression(_e);
    }

    protected virtual void VisitLetGuard(BoundLetGuard node)
    {
    VisitExpression(node.Initializer);
    VisitBlockStatement(node.ElseBody);
    }

    protected virtual void VisitForEachStatement(BoundForEachStatement node)
    {
    VisitExpression(node.Collection);
    VisitStatement(node.Body);
    }

    protected virtual void VisitMatchStatement(BoundMatchStatement node)
    {
    VisitExpression(node.Subject);
    VisitExpression(node.Subject);
    foreach (var _arm in node.Arms)
    {
        if (_arm.Guard is {} _g) VisitExpression(_g);
        VisitBlockStatement(_arm.Body);
    }
    }

    protected virtual void VisitDeferStatement(BoundDeferStatement node)
    {
    VisitBlockStatement(node.Body);
    }

    protected virtual void VisitAsyncLetStatement(BoundAsyncLetStatement node)
    {
    VisitExpression(node.Initializer);
    }

    protected virtual void VisitYieldStatement(BoundYieldStatement node)
    {
    VisitExpression(node.Value);
    }

    protected virtual void VisitSelectStatement(BoundSelectStatement node)
    {
    foreach (var _arm in node.Arms)
    {
        if (_arm.Channel is {} _ch) VisitExpression(_ch);
        if (_arm.Value   is {} _v)  VisitExpression(_v);
        VisitBlockStatement(_arm.Body);
    }
    }

    protected virtual void VisitCompoundAssignment(BoundCompoundAssignment node)
    {
    VisitExpression(node.Target);
    VisitExpression(node.Value);
    }

    // ---- Expressions ----
    protected virtual void VisitExpression(BoundExpression expr) => VisitNode(expr);

    // CORE
    protected virtual void VisitErrorExpression(BoundErrorExpression node) { }

    protected virtual void VisitLiteralExpression(BoundLiteralExpression node) { }

    protected virtual void VisitNameExpression(BoundNameExpression node) { }

    protected virtual void VisitUnaryExpression(BoundUnaryExpression node)
    {
    VisitExpression(node.Operand);
    }

    protected virtual void VisitBinaryExpression(BoundBinaryExpression node)
    {
    VisitExpression(node.Left);
    VisitExpression(node.Right);
    }

    protected virtual void VisitMemberAccessExpression(BoundMemberAccessExpression node)
    {
    VisitExpression(node.Target);
    }

    protected virtual void VisitConversion(BoundConversion node)
    {
    VisitExpression(node.Operand);
    }

    protected virtual void VisitTypeTestExpression(BoundTypeTestExpression node)
    {
    VisitExpression(node.Operand);
    }

    protected virtual void VisitCallExpression(BoundCallExpression node)
    {
    VisitExpression(node.Target);
    foreach (var _e in node.Arguments) VisitExpression(_e);
    }

    protected virtual void VisitObjectCreationExpression(BoundObjectCreationExpression node)
    {
    foreach (var _f in node.Fields) VisitExpression(_f.Value);
    foreach (var _e in node.ConstructorArguments) VisitExpression(_e);
    }

    protected virtual void VisitIndexExpression(BoundIndexExpression node)
    {
    VisitExpression(node.Target);
    VisitExpression(node.Index);
    }

    protected virtual void VisitArrayCreationExpression(BoundArrayCreationExpression node)
    {
    VisitExpression(node.Size);
    }

    protected virtual void VisitStackAllocExpression(BoundStackAllocExpression node)
    {
    VisitExpression(node.Size);
    }

    protected virtual void VisitTupleLiteralExpression(BoundTupleLiteralExpression node)
    {
    foreach (var _e in node.Elements) VisitExpression(_e);
    }

    protected virtual void VisitDefaultExpression(BoundDefaultExpression node) { }

    protected virtual void VisitOutArgumentExpression(BoundOutArgumentExpression node) { }

    protected virtual void VisitAddressOfExpression(BoundAddressOfExpression node) { }

    protected virtual void VisitMethodGroupConversion(BoundMethodGroupConversion node)
    {
    if (node.Receiver is {} _r) VisitExpression(_r);
    }

    protected virtual void VisitAddressOfVariableExpression(BoundAddressOfVariableExpression node)
    {
    VisitExpression(node.Target);
    }

    protected virtual void VisitHeapAllocExpression(BoundHeapAllocExpression node)
    {
    VisitExpression(node.Inner);
    }

    protected virtual void VisitInterpolatedStringExpression(BoundInterpolatedStringExpression node)
    {
    foreach (var _p in node.Parts)
        if (_p.Expr is {} _e) VisitExpression(_e);
    }

    protected virtual void VisitConditionalExpression(BoundConditionalExpression node)
    {
    VisitExpression(node.Condition);
    VisitExpression(node.Consequence);
    VisitExpression(node.Alternative);
    }

    // FEATURE
    protected virtual void VisitNullCoalescingExpression(BoundNullCoalescingExpression node)
    {
    VisitExpression(node.Left);
    VisitExpression(node.Right);
    }

    protected virtual void VisitNullConditionalAccessExpression(BoundNullConditionalAccessExpression node)
    {
    VisitExpression(node.Target);
    }

    protected virtual void VisitListLiteralExpression(BoundListLiteralExpression node)
    {
    foreach (var _e in node.Elements) VisitExpression(_e);
    }

    protected virtual void VisitRangeExpression(BoundRangeExpression node)
    {
    if (node.Target is {} _t) VisitExpression(_t);
    if (node.Start is {} _s) VisitExpression(_s);
    if (node.End is {} _e) VisitExpression(_e);
    }

    protected virtual void VisitSpawnExpression(BoundSpawnExpression node)
    {
    VisitBlockStatement(node.Body);
    }

    protected virtual void VisitChanCreationExpression(BoundChanCreationExpression node)
    {
    if (node.Capacity is {} _c) VisitExpression(_c);
    }

    protected virtual void VisitDotCaseExpression(BoundDotCaseExpression node)
    {
    foreach (var _e in node.Arguments) VisitExpression(_e);
    }

    protected virtual void VisitTryUnwrapExpression(BoundTryUnwrapExpression node)
    {
    VisitExpression(node.Inner);
    }

    protected virtual void VisitWithExpression(BoundWithExpression node)
    {
    VisitExpression(node.Target);
    foreach (var _f in node.Fields) VisitExpression(_f.Value);
    }

    protected virtual void VisitResultCallExpression(BoundResultCallExpression node)
    {
    VisitExpression(node.Argument);
    }

    protected virtual void VisitFunctionLiteralExpression(BoundFunctionLiteralExpression node)
    {
    VisitBlockStatement(node.Body);
    }

    protected virtual void VisitAwaitExpression(BoundAwaitExpression node)
    {
    VisitExpression(node.Inner);
    }

    protected virtual void VisitMatchExpression(BoundMatchExpression node)
    {
    VisitExpression(node.Subject);
    VisitExpression(node.Subject);
    foreach (var _arm in node.Arms)
    {
        if (_arm.Guard is {} _g) VisitExpression(_g);
        VisitExpression(_arm.Value);
    }
    }

    protected virtual void VisitIfExpression(BoundIfExpression node)
    {
    foreach (var _b in node.Branches)
    {
        VisitExpression(_b.Condition);
        foreach (var _s in _b.Body) VisitStatement(_s);
        if (_b.Value is {} _v) VisitExpression(_v);
    }
    foreach (var _s in node.ElseBody) VisitStatement(_s);
    if (node.ElseValue is {} _ev) VisitExpression(_ev);
    foreach (var _s in node.ElseBody) VisitStatement(_s);
    if (node.ElseValue is {} _e) VisitExpression(_e);
    }

}

// ---------------------------------------------------------------------------
// Generic typed visitor (fold / accumulate)
// ---------------------------------------------------------------------------

public abstract class BoundTreeVisitor<T>
{
    public virtual T VisitNode(BoundNode node) => node switch
    {
        // Top-level
        BoundCompilationUnit _n                    => VisitCompilationUnit(_n),
        // Members
        BoundFunctionDeclaration _n                => VisitFunctionDeclaration(_n),
        BoundDataDeclaration _n                    => VisitDataDeclaration(_n),
        BoundInitDeclaration _n                    => VisitInitDeclaration(_n),
        BoundNamespaceInitDeclaration _n           => VisitNamespaceInitDeclaration(_n),
        BoundNamespaceStateDeclaration _n          => VisitNamespaceStateDeclaration(_n),
        BoundInterfaceDeclaration _n               => VisitInterfaceDeclaration(_n),
        BoundDelegateDeclaration _n                => VisitDelegateDeclaration(_n),
        BoundStaticFuncDeclaration _n              => VisitStaticFuncDeclaration(_n),
        BoundConstDeclaration _n                   => VisitConstDeclaration(_n),
        BoundChoiceDeclaration _n                  => VisitChoiceDeclaration(_n),
        BoundEnumDeclaration _n                    => VisitEnumDeclaration(_n),
        // Statements — CORE
        BoundBlockStatement _n                     => VisitBlockStatement(_n),
        BoundVariableDeclaration _n                => VisitVariableDeclaration(_n),
        BoundAssignment _n                         => VisitAssignment(_n),
        BoundIfStatement _n                        => VisitIfStatement(_n),
        BoundWhileStatement _n                     => VisitWhileStatement(_n),
        BoundReturnStatement _n                    => VisitReturnStatement(_n),
        BoundBreakStatement _n                     => VisitBreakStatement(_n),
        BoundContinueStatement _n                  => VisitContinueStatement(_n),
        BoundLabelStatement _n                     => VisitLabelStatement(_n),
        BoundGotoStatement _n                      => VisitGotoStatement(_n),
        BoundExpressionStatement _n                => VisitExpressionStatement(_n),
        BoundScopedMutCall _n                      => VisitScopedMutCall(_n),
        BoundTryStatement _n                       => VisitTryStatement(_n),
        BoundThrowStatement _n                     => VisitThrowStatement(_n),
        BoundConstStatement _n                     => VisitConstStatement(_n),
        // Statements — FEATURE
        BoundRaiseStatement _n                     => VisitRaiseStatement(_n),
        BoundLetGuard _n                           => VisitLetGuard(_n),
        BoundForEachStatement _n                   => VisitForEachStatement(_n),
        BoundMatchStatement _n                     => VisitMatchStatement(_n),
        BoundDeferStatement _n                     => VisitDeferStatement(_n),
        BoundAsyncLetStatement _n                  => VisitAsyncLetStatement(_n),
        BoundYieldStatement _n                     => VisitYieldStatement(_n),
        BoundSelectStatement _n                    => VisitSelectStatement(_n),
        BoundCompoundAssignment _n                 => VisitCompoundAssignment(_n),
        // Expressions — CORE
        BoundErrorExpression _n                    => VisitErrorExpression(_n),
        BoundLiteralExpression _n                  => VisitLiteralExpression(_n),
        BoundNameExpression _n                     => VisitNameExpression(_n),
        BoundUnaryExpression _n                    => VisitUnaryExpression(_n),
        BoundBinaryExpression _n                   => VisitBinaryExpression(_n),
        BoundMemberAccessExpression _n             => VisitMemberAccessExpression(_n),
        BoundConversion _n                         => VisitConversion(_n),
        BoundTypeTestExpression _n                 => VisitTypeTestExpression(_n),
        BoundCallExpression _n                     => VisitCallExpression(_n),
        BoundObjectCreationExpression _n           => VisitObjectCreationExpression(_n),
        BoundIndexExpression _n                    => VisitIndexExpression(_n),
        BoundArrayCreationExpression _n            => VisitArrayCreationExpression(_n),
        BoundStackAllocExpression _n               => VisitStackAllocExpression(_n),
        BoundTupleLiteralExpression _n             => VisitTupleLiteralExpression(_n),
        BoundDefaultExpression _n                  => VisitDefaultExpression(_n),
        BoundOutArgumentExpression _n              => VisitOutArgumentExpression(_n),
        BoundAddressOfExpression _n                => VisitAddressOfExpression(_n),
        BoundMethodGroupConversion _n              => VisitMethodGroupConversion(_n),
        BoundAddressOfVariableExpression _n        => VisitAddressOfVariableExpression(_n),
        BoundHeapAllocExpression _n                => VisitHeapAllocExpression(_n),
        BoundInterpolatedStringExpression _n       => VisitInterpolatedStringExpression(_n),
        BoundConditionalExpression _n              => VisitConditionalExpression(_n),
        // Expressions — FEATURE
        BoundNullCoalescingExpression _n           => VisitNullCoalescingExpression(_n),
        BoundNullConditionalAccessExpression _n    => VisitNullConditionalAccessExpression(_n),
        BoundListLiteralExpression _n              => VisitListLiteralExpression(_n),
        BoundRangeExpression _n                    => VisitRangeExpression(_n),
        BoundSpawnExpression _n                    => VisitSpawnExpression(_n),
        BoundChanCreationExpression _n             => VisitChanCreationExpression(_n),
        BoundDotCaseExpression _n                  => VisitDotCaseExpression(_n),
        BoundTryUnwrapExpression _n                => VisitTryUnwrapExpression(_n),
        BoundWithExpression _n                     => VisitWithExpression(_n),
        BoundResultCallExpression _n               => VisitResultCallExpression(_n),
        BoundFunctionLiteralExpression _n          => VisitFunctionLiteralExpression(_n),
        BoundAwaitExpression _n                    => VisitAwaitExpression(_n),
        BoundMatchExpression _n                    => VisitMatchExpression(_n),
        BoundIfExpression _n                       => VisitIfExpression(_n),

        _ => VisitUnknown(node),
    };

    protected abstract T DefaultResult { get; }
    protected virtual T VisitUnknown(BoundNode node) => DefaultResult;

    // Top-level
    protected virtual T VisitCompilationUnit(BoundCompilationUnit node) => DefaultResult;

    // Members
    protected virtual T VisitFunctionDeclaration(BoundFunctionDeclaration node) => DefaultResult;
    protected virtual T VisitDataDeclaration(BoundDataDeclaration node) => DefaultResult;
    protected virtual T VisitInitDeclaration(BoundInitDeclaration node) => DefaultResult;
    protected virtual T VisitNamespaceInitDeclaration(BoundNamespaceInitDeclaration node) => DefaultResult;
    protected virtual T VisitNamespaceStateDeclaration(BoundNamespaceStateDeclaration node) => DefaultResult;
    protected virtual T VisitInterfaceDeclaration(BoundInterfaceDeclaration node) => DefaultResult;
    protected virtual T VisitDelegateDeclaration(BoundDelegateDeclaration node) => DefaultResult;
    protected virtual T VisitStaticFuncDeclaration(BoundStaticFuncDeclaration node) => DefaultResult;
    protected virtual T VisitConstDeclaration(BoundConstDeclaration node) => DefaultResult;
    protected virtual T VisitChoiceDeclaration(BoundChoiceDeclaration node) => DefaultResult;
    protected virtual T VisitEnumDeclaration(BoundEnumDeclaration node) => DefaultResult;

    // Statements — CORE
    protected virtual T VisitBlockStatement(BoundBlockStatement node) => DefaultResult;
    protected virtual T VisitVariableDeclaration(BoundVariableDeclaration node) => DefaultResult;
    protected virtual T VisitAssignment(BoundAssignment node) => DefaultResult;
    protected virtual T VisitIfStatement(BoundIfStatement node) => DefaultResult;
    protected virtual T VisitWhileStatement(BoundWhileStatement node) => DefaultResult;
    protected virtual T VisitReturnStatement(BoundReturnStatement node) => DefaultResult;
    protected virtual T VisitBreakStatement(BoundBreakStatement node) => DefaultResult;
    protected virtual T VisitContinueStatement(BoundContinueStatement node) => DefaultResult;
    protected virtual T VisitLabelStatement(BoundLabelStatement node) => DefaultResult;
    protected virtual T VisitGotoStatement(BoundGotoStatement node) => DefaultResult;
    protected virtual T VisitExpressionStatement(BoundExpressionStatement node) => DefaultResult;
    protected virtual T VisitScopedMutCall(BoundScopedMutCall node) => DefaultResult;
    protected virtual T VisitTryStatement(BoundTryStatement node) => DefaultResult;
    protected virtual T VisitThrowStatement(BoundThrowStatement node) => DefaultResult;
    protected virtual T VisitConstStatement(BoundConstStatement node) => DefaultResult;

    // Statements — FEATURE
    protected virtual T VisitRaiseStatement(BoundRaiseStatement node) => DefaultResult;
    protected virtual T VisitLetGuard(BoundLetGuard node) => DefaultResult;
    protected virtual T VisitForEachStatement(BoundForEachStatement node) => DefaultResult;
    protected virtual T VisitMatchStatement(BoundMatchStatement node) => DefaultResult;
    protected virtual T VisitDeferStatement(BoundDeferStatement node) => DefaultResult;
    protected virtual T VisitAsyncLetStatement(BoundAsyncLetStatement node) => DefaultResult;
    protected virtual T VisitYieldStatement(BoundYieldStatement node) => DefaultResult;
    protected virtual T VisitSelectStatement(BoundSelectStatement node) => DefaultResult;
    protected virtual T VisitCompoundAssignment(BoundCompoundAssignment node) => DefaultResult;

    // Expressions — CORE
    protected virtual T VisitErrorExpression(BoundErrorExpression node) => DefaultResult;
    protected virtual T VisitLiteralExpression(BoundLiteralExpression node) => DefaultResult;
    protected virtual T VisitNameExpression(BoundNameExpression node) => DefaultResult;
    protected virtual T VisitUnaryExpression(BoundUnaryExpression node) => DefaultResult;
    protected virtual T VisitBinaryExpression(BoundBinaryExpression node) => DefaultResult;
    protected virtual T VisitMemberAccessExpression(BoundMemberAccessExpression node) => DefaultResult;
    protected virtual T VisitConversion(BoundConversion node) => DefaultResult;
    protected virtual T VisitTypeTestExpression(BoundTypeTestExpression node) => DefaultResult;
    protected virtual T VisitCallExpression(BoundCallExpression node) => DefaultResult;
    protected virtual T VisitObjectCreationExpression(BoundObjectCreationExpression node) => DefaultResult;
    protected virtual T VisitIndexExpression(BoundIndexExpression node) => DefaultResult;
    protected virtual T VisitArrayCreationExpression(BoundArrayCreationExpression node) => DefaultResult;
    protected virtual T VisitStackAllocExpression(BoundStackAllocExpression node) => DefaultResult;
    protected virtual T VisitTupleLiteralExpression(BoundTupleLiteralExpression node) => DefaultResult;
    protected virtual T VisitDefaultExpression(BoundDefaultExpression node) => DefaultResult;
    protected virtual T VisitOutArgumentExpression(BoundOutArgumentExpression node) => DefaultResult;
    protected virtual T VisitAddressOfExpression(BoundAddressOfExpression node) => DefaultResult;
    protected virtual T VisitMethodGroupConversion(BoundMethodGroupConversion node) => DefaultResult;
    protected virtual T VisitAddressOfVariableExpression(BoundAddressOfVariableExpression node) => DefaultResult;
    protected virtual T VisitHeapAllocExpression(BoundHeapAllocExpression node) => DefaultResult;
    protected virtual T VisitInterpolatedStringExpression(BoundInterpolatedStringExpression node) => DefaultResult;
    protected virtual T VisitConditionalExpression(BoundConditionalExpression node) => DefaultResult;

    // Expressions — FEATURE
    protected virtual T VisitNullCoalescingExpression(BoundNullCoalescingExpression node) => DefaultResult;
    protected virtual T VisitNullConditionalAccessExpression(BoundNullConditionalAccessExpression node) => DefaultResult;
    protected virtual T VisitListLiteralExpression(BoundListLiteralExpression node) => DefaultResult;
    protected virtual T VisitRangeExpression(BoundRangeExpression node) => DefaultResult;
    protected virtual T VisitSpawnExpression(BoundSpawnExpression node) => DefaultResult;
    protected virtual T VisitChanCreationExpression(BoundChanCreationExpression node) => DefaultResult;
    protected virtual T VisitDotCaseExpression(BoundDotCaseExpression node) => DefaultResult;
    protected virtual T VisitTryUnwrapExpression(BoundTryUnwrapExpression node) => DefaultResult;
    protected virtual T VisitWithExpression(BoundWithExpression node) => DefaultResult;
    protected virtual T VisitResultCallExpression(BoundResultCallExpression node) => DefaultResult;
    protected virtual T VisitFunctionLiteralExpression(BoundFunctionLiteralExpression node) => DefaultResult;
    protected virtual T VisitAwaitExpression(BoundAwaitExpression node) => DefaultResult;
    protected virtual T VisitMatchExpression(BoundMatchExpression node) => DefaultResult;
    protected virtual T VisitIfExpression(BoundIfExpression node) => DefaultResult;

}
// BoundNode is defined in BoundNodes.cs as the shared abstract class base.
