using System.Text;
using Esharp.Compiler.Binding;
using Esharp.Compiler.Syntax;

namespace Esharp.Compiler.Emit;

public sealed class CSharpEmitter
{
    StringBuilder _builder = new();
    readonly string _sourcePath;
    int _indent;
    string? _selfParamName; // Set when emitting an instance method body

    CSharpEmitter(string sourcePath) => _sourcePath = sourcePath;

    public static string Emit(BoundCompilationUnit unit, string sourcePath = "input.es")
    {
        var emitter = new CSharpEmitter(sourcePath);
        emitter.EmitCompilationUnit(unit);
        return emitter._builder.ToString();
    }

    void EmitCompilationUnit(BoundCompilationUnit unit)
    {
        WriteLine("// <auto-generated />");
        WriteLine("using System;");
        WriteLine("using System.Collections.Generic;");
        WriteLine("using System.Threading.Tasks;");
        WriteLine("using Esharp.Runtime;");
        foreach (var ns in unit.Imports)
            WriteLine($"using {ns};");
        WriteLine();
        WriteLine("namespace Esharp.Generated;");
        WriteLine();

        foreach (var member in unit.Members)
        {
            switch (member)
            {
                case BoundProtocolDeclaration p: EmitProtocol(p); WriteLine(); break;
                case BoundEnumDeclaration e: EmitEnum(e); WriteLine(); break;
                case BoundDataDeclaration d: EmitData(d); WriteLine(); break;
                case BoundChoiceDeclaration c: EmitChoice(c); WriteLine(); break;
            }
        }

        // Static functions (non-instance-methods)
        var staticFunctions = unit.Members.OfType<BoundFunctionDeclaration>().ToList();
        if (staticFunctions.Count > 0)
        {
            var moduleName = string.IsNullOrWhiteSpace(unit.ModuleName) ? "Main" : unit.ModuleName!;
            WriteLine($"public static partial class {moduleName}");
            WriteLine("{");
            _indent++;

            foreach (var member in staticFunctions)
            {
                EmitFunction(member);
                WriteLine();
            }

            _indent--;
            WriteLine("}");
        }
    }

    void EmitEnum(BoundEnumDeclaration e)
    {
        WriteLine($"public enum {e.Name}");
        WriteLine("{");
        _indent++;
        for (var i = 0; i < e.Cases.Count; i++)
            WriteLine($"{e.Cases[i]}{(i < e.Cases.Count - 1 ? "," : "")}");
        _indent--;
        WriteLine("}");
    }

    void EmitProtocol(BoundProtocolDeclaration p)
    {
        WriteLine($"public interface {p.Name}");
        WriteLine("{");
        _indent++;
        foreach (var m in p.Methods)
        {
            var parameters = string.Join(", ", m.Parameters.Select(pp => $"{pp.Type.EmitName} {pp.Name}"));
            WriteLine($"{m.ReturnType.EmitName} {m.Name}({parameters});");
        }
        _indent--;
        WriteLine("}");
    }

    void EmitData(BoundDataDeclaration d)
    {
        var typeParams = d.TypeParameters.Count > 0 ? $"<{string.Join(", ", d.TypeParameters)}>" : "";
        var interfaceList = d.Interfaces.Count > 0 ? $" : {string.Join(", ", d.Interfaces)}" : "";
        WriteLine($"public partial struct {d.Name}{typeParams}{interfaceList}");
        WriteLine("{");
        _indent++;
        foreach (var f in d.Fields)
            WriteLine($"public {f.Type.EmitName} {f.Name};");

        // Instance methods — first param removed (it's `this`)
        foreach (var m in d.InstanceMethods)
        {
            WriteLine();
            var parameters = string.Join(", ", m.Parameters.Skip(1).Select(pp =>
                pp.ByRef ? $"ref {pp.Type.EmitName} {pp.Name}" : $"{pp.Type.EmitName} {pp.Name}"));
            var methodTypeParams = m.TypeParameters.Count > 0 ? $"<{string.Join(", ", m.TypeParameters)}>" : "";
            var asyncPrefix = "";
            var retType = m.ReturnType.EmitName;
            if (m.HasAwait)
            {
                asyncPrefix = "async ";
                retType = m.ReturnType is VoidType ? "ValueTask" : $"ValueTask<{retType}>";
            }
            WriteLine($"public {asyncPrefix}{retType} {m.Name}{methodTypeParams}({parameters})");
            WriteLine("{");
            _indent++;
            _selfParamName = m.Parameters[0].Name;
            EmitBlock(m.Body);
            _selfParamName = null;
            _indent--;
            WriteLine("}");
        }

        // Derive: equality
        if (d.DeriveTraits.Contains("equality"))
        {
            var fieldNames = d.Fields.Select(f => f.Name).ToList();
            WriteLine();
            WriteLine($"public bool Equals({d.Name} other)");
            WriteLine("{");
            _indent++;
            if (fieldNames.Count == 0)
                WriteLine("return true;");
            else
            {
                var checks = string.Join(" && ", fieldNames.Select(n => $"Equals({n}, other.{n})"));
                WriteLine($"return {checks};");
            }
            _indent--;
            WriteLine("}");
            WriteLine();
            WriteLine("public override bool Equals(object obj) => obj is " + d.Name + " other && Equals(other);");
            WriteLine();
            WriteLine("public override int GetHashCode()");
            WriteLine("{");
            _indent++;
            if (fieldNames.Count == 0)
                WriteLine("return 0;");
            else
            {
                WriteLine($"return HashCode.Combine({string.Join(", ", fieldNames)});");
            }
            _indent--;
            WriteLine("}");
        }

        // Derive: debug (ToString)
        if (d.DeriveTraits.Contains("debug"))
        {
            var fieldNames = d.Fields.Select(f => f.Name).ToList();
            WriteLine();
            WriteLine("public override string ToString()");
            WriteLine("{");
            _indent++;
            if (fieldNames.Count == 0)
                WriteLine($"return \"{d.Name} {{}}\";");
            else
            {
                var parts = string.Join(", ", fieldNames.Select(n => $"{n}={{{n}}}"));
                WriteLine($"return $\"{d.Name} {{ {parts} }}\";");
            }
            _indent--;
            WriteLine("}");
        }

        _indent--;
        WriteLine("}");
    }

    void EmitChoice(BoundChoiceDeclaration c)
    {
        var typeParams = c.TypeParameters.Count > 0 ? $"<{string.Join(", ", c.TypeParameters)}>" : "";
        var fullName = $"{c.Name}{typeParams}";
        var tagName = $"{c.Name}Tag";
        WriteLine($"public enum {tagName}");
        WriteLine("{");
        _indent++;
        for (var i = 0; i < c.Cases.Count; i++)
            WriteLine($"{c.Cases[i].Name}{(i < c.Cases.Count - 1 ? "," : "")}");
        _indent--;
        WriteLine("}");
        WriteLine();

        WriteLine($"public partial struct {fullName}");
        WriteLine("{");
        _indent++;
        WriteLine($"public {tagName} Tag;");

        foreach (var cc in c.Cases.Where(x => x.PayloadType is not null))
            WriteLine($"public {cc.PayloadType!.EmitName} _{cc.Name}_{cc.PayloadName};");

        WriteLine();

        foreach (var cc in c.Cases)
        {
            if (cc.PayloadType is null)
            {
                WriteLine($"public static {fullName} {cc.Name}()");
                WriteLine("{");
                _indent++;
                WriteLine($"return new {fullName} {{ Tag = {tagName}.{cc.Name} }};");
                _indent--;
                WriteLine("}");
            }
            else
            {
                WriteLine($"public static {fullName} {cc.Name}({cc.PayloadType.EmitName} {cc.PayloadName})");
                WriteLine("{");
                _indent++;
                WriteLine($"return new {fullName}");
                WriteLine("{");
                _indent++;
                WriteLine($"Tag = {tagName}.{cc.Name},");
                WriteLine($"_{cc.Name}_{cc.PayloadName} = {cc.PayloadName},");
                _indent--;
                WriteLine("};");
                _indent--;
                WriteLine("}");
            }
        }

        _indent--;
        WriteLine("}");
    }

    void EmitFunction(BoundFunctionDeclaration f)
    {
        var parameters = string.Join(", ", f.Parameters.Select(p =>
            p.ByRef ? $"ref {p.Type.EmitName} {p.Name}" : $"{p.Type.EmitName} {p.Name}"));

        var typeParams = f.TypeParameters.Count > 0 ? $"<{string.Join(", ", f.TypeParameters)}>" : "";

        // func main() → public static void Main() (or int Main())
        var emitName = f.Name == "main" ? "Main" : f.Name;

        // Async functions: add async keyword, wrap return type in ValueTask<T>
        var asyncPrefix = "";
        var emitReturn = f.ReturnType.EmitName;
        if (f.HasAwait)
        {
            asyncPrefix = "async ";
            emitReturn = f.ReturnType is VoidType ? "ValueTask" : $"ValueTask<{emitReturn}>";
        }

        WriteLine($"public static {asyncPrefix}{emitReturn} {emitName}{typeParams}({parameters})");
        WriteLine("{");
        _indent++;
        WriteLine($"#line 1 \"{_sourcePath}\"");
        EmitBlock(f.Body);
        WriteLine("#line default");
        WriteLine("#line hidden");
        _indent--;
        WriteLine("}");
    }

    void EmitBlock(BoundBlockStatement block)
    {
        var defers = block.Statements.OfType<BoundDeferStatement>().ToList();
        if (defers.Count == 0)
        {
            foreach (var s in block.Statements) EmitStatement(s);
            return;
        }

        WriteLine("try");
        WriteLine("{");
        _indent++;
        foreach (var s in block.Statements)
            if (s is not BoundDeferStatement) EmitStatement(s);
        _indent--;
        WriteLine("}");
        WriteLine("finally");
        WriteLine("{");
        _indent++;
        foreach (var d in Enumerable.Reverse(defers)) EmitBlock(d.Body);
        _indent--;
        WriteLine("}");
    }

    void EmitStatement(BoundStatement statement)
    {
        switch (statement)
        {
            case BoundVariableDeclaration v:
                EmitVarDecl(v);
                break;
            case BoundLetGuard g:
                EmitLetGuard(g);
                break;
            case BoundAssignment a:
                WriteLine($"{EmitExpr(a.Target)} = {EmitExpr(a.Value)};");
                break;
            case BoundCompoundAssignment ca:
                WriteLine($"{EmitExpr(ca.Target)} {CompoundOp(ca.Op)}= {EmitExpr(ca.Value)};");
                break;
            case BoundIfStatement i:
                EmitIf(i);
                break;
            case BoundWhileStatement w:
                WriteLine($"while ({EmitExpr(w.Condition)})");
                EmitEmbedded(w.Body);
                break;
            case BoundForEachStatement f:
                WriteLine($"foreach (var {f.Identifier} in {EmitExpr(f.Collection)})");
                EmitEmbedded(f.Body);
                break;
            case BoundReturnStatement r:
                WriteLine(r.Expression is null ? "return;" : $"return {EmitExpr(r.Expression)};");
                break;
            case BoundExpressionStatement e:
                WriteLine($"{EmitExpr(e.Expression)};");
                break;
            case BoundBlockStatement b:
                WriteLine("{");
                _indent++;
                EmitBlock(b);
                _indent--;
                WriteLine("}");
                break;
            case BoundMatchStatement m:
                EmitMatch(m);
                break;
            case BoundDeferStatement:
                break; // handled by EmitBlock
        }
    }

    void EmitVarDecl(BoundVariableDeclaration v)
    {
        if (v.Initializer is BoundTryUnwrapExpression tu)
        {
            EmitTryUnwrapDecl(v.Name, v.DeclaredType, tu);
            return;
        }

        var typeName = v.DeclaredType is ExternalType { Name: "var" } ? "var" :
                       v.DeclaredType is NullType ? "var" : v.DeclaredType.EmitName;
        // Use 'var' when type was inferred from initializer and isn't a known E# type
        if (typeName != "var" && v.DeclaredType is ExternalType) typeName = "var";
        WriteLine($"var {v.Name} = {EmitExpr(v.Initializer)};");
    }

    void EmitTryUnwrapDecl(string name, BoundType declaredType, BoundTryUnwrapExpression tu)
    {
        var temp = tu.TempName;
        WriteLine($"var {temp} = {EmitExpr(tu.Inner)};");

        if (tu.Inner.Type is ResultType rt)
            WriteLine($"if ({temp}.IsError) return Result.Error<{rt.OkType.EmitName}, {rt.ErrorType.EmitName}>({temp}.ErrorValue);");
        else
            WriteLine($"if ({temp}.IsError) throw new InvalidOperationException(\"Unwrap failed\");");

        WriteLine($"var {name} = {temp}.Value;");
    }

    void EmitLetGuard(BoundLetGuard g)
    {
        WriteLine($"var {g.Name} = {EmitExpr(g.Initializer)};");
        WriteLine($"if ({g.Name} == null)");
        WriteLine("{");
        _indent++;
        EmitBlock(g.ElseBody);
        _indent--;
        WriteLine("}");
    }

    void EmitIf(BoundIfStatement i)
    {
        WriteLine($"if ({EmitExpr(i.Condition)})");
        EmitEmbedded(i.Then);
        if (i.Else is not null)
        {
            WriteLine("else");
            EmitEmbedded(i.Else);
        }
    }

    void EmitEmbedded(BoundStatement statement)
    {
        if (statement is BoundBlockStatement block)
        {
            WriteLine("{");
            _indent++;
            EmitBlock(block);
            _indent--;
            WriteLine("}");
            return;
        }
        _indent++;
        EmitStatement(statement);
        _indent--;
    }

    void EmitMatch(BoundMatchStatement m)
    {
        var subjectExpr = EmitExpr(m.Subject);
        var typeName = m.SubjectType.EmitName;
        var tagEnum = $"{typeName}Tag";

        WriteLine($"switch ({subjectExpr}.Tag)");
        WriteLine("{");
        _indent++;

        foreach (var arm in m.Arms)
        {
            if (arm.Pattern.IsDefault)
                WriteLine("default:");
            else
                WriteLine($"case {tagEnum}.{arm.Pattern.CaseName}:");

            WriteLine("{");
            _indent++;

            if (!arm.Pattern.IsDefault && arm.Pattern.BindingName is not null && arm.Pattern.BindingType is not null)
                WriteLine($"var {arm.Pattern.BindingName} = {subjectExpr}._{arm.Pattern.CaseName}_{arm.Pattern.BindingName};");

            EmitBlock(arm.Body);
            if (!ArmTerminates(arm.Body))
                WriteLine("break;");
            _indent--;
            WriteLine("}");
        }

        _indent--;
        WriteLine("}");
    }

    // === Expression emission ===

    string EmitExpr(BoundExpression expr) =>
        expr switch
        {
            BoundLiteralExpression lit => EmitLiteral(lit),
            BoundNameExpression name => name.Name == _selfParamName ? "this" : name.Name,
            BoundUnaryExpression u => EmitUnary(u),
            BoundBinaryExpression b => EmitBinary(b),
            BoundMemberAccessExpression ma => $"{EmitExpr(ma.Target)}.{ma.MemberName}",
            BoundCallExpression call => EmitCall(call),
            BoundResultCallExpression rc => EmitResultCall(rc),
            BoundObjectCreationExpression oc => EmitObjectCreation(oc),
            BoundParenthesizedExpression p => $"({EmitExpr(p.Inner)})",
            BoundIndexExpression idx => $"{EmitExpr(idx.Target)}[{EmitExpr(idx.Index)}]",
            BoundRangeExpression range => EmitRange(range),
            BoundSpawnExpression spawn => EmitSpawn(spawn),
            BoundChanCreationExpression chan => $"new Chan<{chan.ElementType.EmitName}>({(chan.Capacity is not null ? EmitExpr(chan.Capacity) : "")})",
            BoundDotCaseExpression dot => EmitDotCase(dot),
            BoundFunctionLiteralExpression fl => EmitFunctionLiteral(fl),
            BoundAddressOfExpression ao => EmitAddressOf(ao),
            BoundAwaitExpression aw => $"(await {EmitExpr(aw.Inner)})",
            BoundTryUnwrapExpression tu => $"({EmitExpr(tu.Inner)}).Value",
            _ => throw new NotSupportedException($"Cannot emit expression type '{expr.GetType().Name}'."),
        };

    string EmitLiteral(BoundLiteralExpression lit) =>
        lit.Value switch
        {
            null => "null",
            string s => s.Contains('{') ? EmitInterpolatedString(lit.Text) : lit.Text,
            bool b => b ? "true" : "false",
            _ => lit.Text,
        };

    string EmitInterpolatedString(string text)
    {
        // Replace self param name with 'this' inside interpolation expressions
        if (_selfParamName is not null)
            text = text.Replace($"{{{_selfParamName}.", "{this.").Replace($"{{{_selfParamName}}}", "{this}");
        return $"${text}";
    }

    string EmitFunctionLiteral(BoundFunctionLiteralExpression fl)
    {
        var prev = _builder;
        var prevIndent = _indent;

        var body = new StringBuilder();
        _builder = body;
        _indent = 1;
        EmitBlock(fl.Body);

        _builder = prev;
        _indent = prevIndent;

        var bodyStr = body.ToString().TrimEnd();
        var parameters = string.Join(", ", fl.Parameters.Select(p => $"{p.Type.EmitName} {p.Name}"));
        var sb = new StringBuilder();
        sb.AppendLine($"({parameters}) =>");
        sb.AppendLine("{");
        if (bodyStr.Length > 0) sb.AppendLine(bodyStr);
        sb.Append(' ', _indent * 4);
        sb.Append("}");
        return sb.ToString();
    }

    string EmitAddressOf(BoundAddressOfExpression ao)
    {
        // Emit as C# unsafe function pointer: (delegate*<params, ret>)&Module.func
        var fpType = (FunctionPointerType)ao.Type;
        return $"(({fpType.EmitName})(&{ao.FunctionName}))";
    }

    string EmitUnary(BoundUnaryExpression u)
    {
        var op = u.Op switch
        {
            SyntaxTokenKind.Bang or SyntaxTokenKind.NotKeyword => "!",
            SyntaxTokenKind.Minus => "-",
            SyntaxTokenKind.Star => "ref ",
            SyntaxTokenKind.Caret => "^",
            _ => throw new NotSupportedException($"Unsupported unary '{u.Op}'."),
        };
        return $"{op}{EmitExpr(u.Operand)}";
    }

    string EmitBinary(BoundBinaryExpression b)
    {
        var op = b.Op switch
        {
            SyntaxTokenKind.Plus => "+",
            SyntaxTokenKind.Minus => "-",
            SyntaxTokenKind.Star => "*",
            SyntaxTokenKind.Slash => "/",
            SyntaxTokenKind.Percent => "%",
            SyntaxTokenKind.EqualsEquals => "==",
            SyntaxTokenKind.BangEquals => "!=",
            SyntaxTokenKind.Less => "<",
            SyntaxTokenKind.LessEquals => "<=",
            SyntaxTokenKind.Greater => ">",
            SyntaxTokenKind.GreaterEquals => ">=",
            SyntaxTokenKind.AmpAmp or SyntaxTokenKind.AndKeyword => "&&",
            SyntaxTokenKind.PipePipe or SyntaxTokenKind.OrKeyword => "||",
            _ => throw new NotSupportedException($"Unsupported binary '{b.Op}'."),
        };
        return $"({EmitExpr(b.Left)} {op} {EmitExpr(b.Right)})";
    }

    string EmitCall(BoundCallExpression call)
    {
        var arguments = call.Arguments;
        // In instance method context: if the first arg is the self param, strip it
        // (the call is to a sibling instance method on the same struct)
        if (_selfParamName is not null && arguments.Count > 0 &&
            arguments[0] is BoundNameExpression firstArg && firstArg.Name == _selfParamName)
        {
            arguments = arguments.Skip(1).ToList();
        }
        var args = string.Join(", ", arguments.Select(EmitCallArg));
        return $"{EmitExpr(call.Target)}({args})";
    }

    string EmitCallArg(BoundExpression arg)
    {
        if (arg is BoundUnaryExpression { Op: SyntaxTokenKind.Star } u)
            return $"ref {EmitExpr(u.Operand)}";
        return EmitExpr(arg);
    }

    string EmitResultCall(BoundResultCallExpression rc)
    {
        var ok = rc.OkType.EmitName;
        var err = rc.ErrorType.EmitName;
        return rc.IsOk
            ? $"Result.Ok<{ok}, {err}>({EmitExpr(rc.Argument)})"
            : $"Result.Error<{ok}, {err}>({EmitExpr(rc.Argument)})";
    }

    string EmitObjectCreation(BoundObjectCreationExpression oc)
    {
        var fields = string.Join(", ", oc.Fields.Select(f => $"{f.Name} = {EmitExpr(f.Value)}"));
        return $"new {oc.ObjectType.EmitName} {{ {fields} }}";
    }

    string EmitRange(BoundRangeExpression range)
    {
        var start = range.Start is not null ? EmitExpr(range.Start) : "";
        var end = range.End is not null ? EmitExpr(range.End) : "";
        return $"{EmitExpr(range.Target)}[{start}..{end}]";
    }

    string EmitSpawn(BoundSpawnExpression spawn)
    {
        var prev = _builder;
        var prevIndent = _indent;

        var body = new StringBuilder();
        _builder = body;
        _indent = 1;
        EmitBlock(spawn.Body);

        _builder = prev;
        _indent = prevIndent;

        var bodyStr = body.ToString().TrimEnd();
        var sb = new StringBuilder();
        sb.AppendLine("Job.Spawn(_ =>");
        sb.AppendLine("{");
        if (bodyStr.Length > 0) sb.AppendLine(bodyStr);
        sb.Append(' ', _indent * 4);
        sb.Append("})");
        return sb.ToString();
    }

    string EmitDotCase(BoundDotCaseExpression dot)
    {
        // Result ok/error
        if (dot.ResolvedTypeName == "Result" && dot.Type is ResultType rt)
        {
            var arg = EmitExpr(dot.Arguments[0]);
            return dot.CaseName == "ok"
                ? $"Result.Ok<{rt.OkType.EmitName}, {rt.ErrorType.EmitName}>({arg})"
                : $"Result.Error<{rt.OkType.EmitName}, {rt.ErrorType.EmitName}>({arg})";
        }

        // Choice case — use full generic type name
        if (dot.Type is ChoiceType ct)
        {
            var args = string.Join(", ", dot.Arguments.Select(EmitExpr));
            return $"{ct.EmitName}.{dot.CaseName}({args})";
        }

        // Enum case
        if (dot.Type is EnumType)
            return $"{dot.ResolvedTypeName}.{dot.CaseName}";

        // Fallback
        var fallbackArgs = string.Join(", ", dot.Arguments.Select(EmitExpr));
        return dot.Arguments.Count > 0 ? $"{dot.CaseName}({fallbackArgs})" : dot.CaseName;
    }

    // === Helpers ===

    static bool ArmTerminates(BoundBlockStatement block)
    {
        if (block.Statements.Count == 0) return false;
        return block.Statements[^1] is BoundReturnStatement;
    }

    static string CompoundOp(SyntaxTokenKind kind) =>
        kind switch
        {
            SyntaxTokenKind.PlusEquals => "+",
            SyntaxTokenKind.MinusEquals => "-",
            SyntaxTokenKind.StarEquals => "*",
            SyntaxTokenKind.SlashEquals => "/",
            _ => throw new NotSupportedException($"Unsupported compound op '{kind}'."),
        };

    void WriteLine(string line = "")
    {
        if (line.Length == 0) { _builder.AppendLine(); return; }
        _builder.Append(' ', _indent * 4);
        _builder.AppendLine(line);
    }
}
